(function(){
'use strict';const Q=CamberQuotes,E=Q.esc;
const itemHTML=(x={})=>`<div class="cq-item"><label>Item<input data-title required maxlength="200" value="${E(x.title||'')}"></label><label>Quantidade<input data-quantity type="number" min="0.01" max="100000" step="0.01" required value="${x.quantity||1}"></label><label>Unidade<select data-unit>${['unidade','conjunto','m²','metro linear'].map(v=>`<option ${x.unit===v?'selected':''}>${v}</option>`).join('')}</select></label><button type="button" class="cq-x" data-remove-item aria-label="Remover item" title="Remover item">×</button></div>`;
const roomHTML=(name='',items=[{}])=>`<section class="cq-room"><div class="cq-row"><label>Nome do cômodo / grupo<input data-room required maxlength="100" placeholder="Ex.: Cozinha" value="${E(name)}"></label><button type="button" class="cq-x" data-remove-room aria-label="Remover cômodo" title="Remover cômodo">×</button></div><div class="cq-items">${items.map(itemHTML).join('')}</div><button class="cq-add-item" type="button">+ Adicionar item neste cômodo</button></section>`;
const group=items=>{const map=new Map();for(const i of items){const room=i.room||'Itens do orçamento';if(!map.has(room))map.set(room,[]);map.get(room).push(i)}return [...map].map(([r,items])=>roomHTML(r,items)).join('')};
function dialog(html){const d=document.createElement('dialog');d.className='cq-dialog';d.innerHTML=html;document.body.append(d);d.onclose=()=>d.remove();d.showModal();return d;}
const link=r=>location.origin+'/responder-proposta.html#token='+encodeURIComponent(r.token);
function linkPanel(r,ctx){const d=dialog(`<div class="cq-row"><h2>Pedido · ${E(r.supplier_name)}</h2><button class="cq-x" data-close aria-label="Fechar">×</button></div><p>${E(r.specification.title)}</p><p>${r.response?'✓ Proposta recebida em '+new Date(r.responded_at).toLocaleString('pt-BR'):!r.active?'Link cancelado':Date.parse(r.expires_at)<Date.now()?'Link expirado':'Aguardando resposta'} · Validade: ${new Date(r.expires_at).toLocaleString('pt-BR')}</p><label>Link individual do fornecedor<input readonly value="${E(link(r))}"></label><div class="cq-row"><button data-copy>Copiar link</button><a href="${E(link(r))}" target="_blank" rel="noopener noreferrer">Abrir como fornecedor ↗</a></div><p class="cq-muted">Compartilhe este link apenas com o fornecedor indicado. Ele permite consultar os anexos e enviar a proposta deste pedido. Nenhum e-mail é enviado.</p><div class="cq-files"></div><p data-status role="status"></p>${r.response?'<button data-details>Ver valores e detalhes recebidos</button>':''}${r.active?'<button data-revoke>Cancelar link</button>':''}`);
 d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(link(r));d.querySelector('[data-status]').textContent='Link copiado.'}catch{d.querySelector('input').select();d.querySelector('[data-status]').textContent='Selecione e copie o link acima.'}};
 d.querySelector('[data-details]')?.addEventListener('click',()=>Q.details(r.response,r.supplier_name));
 d.querySelector('[data-revoke]')?.addEventListener('click',async e=>{e.target.disabled=true;try{await Q.api('revoke',{id:r.id});d.close();await ctx.refresh();}catch(err){d.querySelector('[data-status]').textContent=err.message;e.target.disabled=false}});
 Q.api('files',{id:r.id}).then(data=>{d.querySelector('.cq-files').innerHTML=(data.files||[]).map(f=>`<a href="${E(f.url)}" target="_blank" rel="noopener noreferrer">${E(f.name)} ↓</a>`).join('')}).catch(err=>d.querySelector('[data-status]').textContent=err.message);
}
async function editor(ctx,p){
 let prior=[];try{prior=await Q.api('list',{projectId:String(ctx.projectId),opportunityId:String(ctx.opportunity.id)})}catch(err){alert(err.message);return}
 const last=prior[0]?.specification;let spec=last||{mode:'standard',title:ctx.opportunity.serv,description:ctx.opportunity.titulo||'',items:[{room:'Itens do orçamento',title:'',quantity:1,unit:'unidade'}]};
 let request=null,files=[],fileIds=[],uploaded=0,working=false;const id=crypto.randomUUID();
 const d=dialog(`<form><div class="cq-row"><h2>Solicitar orçamento · ${E(p.name)}</h2><button type="button" class="cq-x" data-close aria-label="Fechar">×</button></div><label>Tipo de pedido<select name="mode"><option value="standard">Modelo padrão</option><option value="custom">Escrever meu pedido</option></select></label><p class="cq-muted">${last?'O último pedido desta oportunidade foi carregado para reutilizar o mesmo escopo.':'Prepare os itens do modelo ou escreva um pedido por cômodo.'} Gerar um novo pedido cria outra cotação e preserva os pedidos anteriores. Para negociar o mesmo escopo, use uma nova rodada na cotação.</p><label>Título do pedido<input name="title" required maxlength="150" value="${E(spec.title)}"></label><label>O que deve ser orçado?<textarea name="description" required maxlength="3000" rows="3">${E(spec.description)}</textarea></label><div data-rooms>${group(spec.items)}</div><button type="button" data-add-room>+ Adicionar cômodo / grupo</button><label>Prazo para o fornecedor responder<input name="deadline" type="date" required value="${new Date(Date.now()+14*86400000).toISOString().slice(0,10)}"></label><label>Anexar projeto<input name="files" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.dwg,.dxf,.zip"></label><p class="cq-muted">Até 10 arquivos de 25 MB cada. Anexos são específicos deste pedido; selecione os arquivos novamente ao reutilizar um modelo.</p><p data-file-list></p><p data-error class="cq-error" role="alert"></p><p data-status role="status"></p><button class="primary" type="submit">Salvar pedido e gerar link</button></form>`);
 const form=d.querySelector('form'),f=form.elements;f.mode.value=spec.mode;
 const appendRoom=()=>{d.querySelector('[data-rooms]').insertAdjacentHTML('beforeend',roomHTML());};
 d.querySelector('[data-add-room]').onclick=appendRoom;
 f.mode.onchange=()=>{if(!last&&f.mode.value==='custom'&&![...d.querySelectorAll('[data-title]')].some(x=>x.value.trim()))d.querySelector('[data-rooms]').innerHTML='';if(!d.querySelector('.cq-room')&&f.mode.value==='standard')d.querySelector('[data-rooms]').innerHTML=roomHTML('Itens do orçamento');};
 f.files.onchange=()=>{files=[...f.files.files];fileIds=files.map(()=>crypto.randomUUID());d.querySelector('[data-file-list]').textContent=files.map(x=>x.name).join(' · ')};
 d.onclick=e=>{if(working)return;if(e.target.closest('[data-close]'))d.close();if(e.target.closest('[data-remove-room]'))e.target.closest('.cq-room').remove();if(e.target.closest('[data-remove-item]'))e.target.closest('.cq-item').remove();if(e.target.closest('.cq-add-item'))e.target.closest('.cq-room').querySelector('.cq-items').insertAdjacentHTML('beforeend',itemHTML())};
 d.addEventListener('cancel',e=>{if(working)e.preventDefault()});
 form.onsubmit=async e=>{e.preventDefault();if(working)return;const err=d.querySelector('[data-error]'),status=d.querySelector('[data-status]');err.textContent='';try{
 const items=[...d.querySelectorAll('.cq-room')].flatMap(room=>[...room.querySelectorAll('.cq-item')].map(row=>({id:crypto.randomUUID(),room:room.querySelector('[data-room]').value.trim(),title:row.querySelector('[data-title]').value.trim(),quantity:Number(row.querySelector('[data-quantity]').value),unit:row.querySelector('[data-unit]').value})));
 if(!items.length)throw Error('Adicione ao menos um cômodo ou grupo com um item.');
 if(files.length>10||files.some(x=>!x.size||x.size>25*1024*1024||!/\.(pdf|png|jpe?g|dwg|dxf|zip)$/i.test(x.name)))throw Error('Confira os anexos: até 10 arquivos válidos de 25 MB.');
 working=true;form.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='Salvando pedido…';
 if(!request)request=await Q.api('create',{id,projectId:String(ctx.projectId),opportunityId:String(ctx.opportunity.id),proposalId:String(p.id),expiresAt:f.deadline.value+'T23:59:59-03:00',specification:{mode:f.mode.value,title:f.title.value,description:f.description.value,items}});
 form.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);
 for(;uploaded<files.length;uploaded++){status.textContent='Enviando anexo '+(uploaded+1)+' de '+files.length+'…';await Q.api('upload',{id:request.id,fileId:fileIds[uploaded]},files[uploaded]);}
 await ctx.refresh();d.close();linkPanel(request,ctx);
 }catch(error){err.textContent=error.message;status.textContent=request?'Pedido salvo. Clique novamente para tentar enviar os anexos restantes.':'';}finally{working=false;form.querySelectorAll('button').forEach(b=>b.disabled=false);if(request)form.querySelectorAll('[data-add-room],[data-remove-room],[data-remove-item],.cq-add-item').forEach(b=>b.disabled=true);}};
}
async function history(ctx,p){try{const rows=(await Q.api('list',{projectId:String(ctx.projectId),opportunityId:String(ctx.opportunity.id)})).filter(r=>r.proposal_id===String(p.id));if(!rows.length){await editor(ctx,p);return}const d=dialog('<div class="cq-row"><h2>Pedidos · '+E(p.name)+'</h2><button class="cq-x" data-close aria-label="Fechar">×</button></div>'+rows.map((r,i)=>'<p><button data-index="'+i+'">'+E(r.specification.title)+' · '+new Date(r.created_at).toLocaleDateString('pt-BR')+' · '+(r.response?'Respondido':!r.active?'Cancelado':Date.parse(r.expires_at)<Date.now()?'Expirado':'Aguardando')+'</button></p>').join(''));d.querySelector('[data-close]').onclick=()=>d.close();d.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>{d.close();linkPanel(rows[Number(b.dataset.index)],ctx)})}catch(e){alert(e.message)}}
Q.editor=editor;Q.history=history;
})();
