(function(){
'use strict';
const Q=CamberQuotes,E=Q.esc,M=CamberQuoteModel;
const date=x=>x?new Date(x).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const href=(q,tab)=>'cotacoes.html?id='+encodeURIComponent(q.id)+(tab?'&tab='+tab:'')+(q.client_key?'&client='+encodeURIComponent(q.client_key):'');
const filters=[['project_name','Projeto'],['client_name','Cliente'],['service','Categoria'],['responsible','Responsável'],['supplier','Fornecedor'],['status','Status']];
const sorts=[['attention','Exigem atenção'],['deadline','Prazo'],['project','Projeto'],['value','Valor estimado'],['responses','Respostas'],['status','Status'],['created','Data de criação']];
const badge=q=>'<span class="cq-badge '+(['READY','CLOSED'].includes(q.status)?'good':q.status==='EXPIRED'?'bad':['DRAFT','CANCELED'].includes(q.status)?'neutral':'wait')+'">'+E(M.labels[q.status]||q.status)+'</span>';
const avatars=q=>'<div class="cq-avatars" aria-label="'+E(q.suppliers.map(s=>s.name).join(', '))+'">'+q.suppliers.slice(0,3).map(s=>'<span tabindex="0" class="cq-avatar-tip" data-name="'+E(s.name)+'" aria-label="'+E(s.name)+'">'+Q.avatar(s.name)+'</span>').join('')+(q.suppliers.length>3?'<span class="cq-avatar" title="'+E(q.suppliers.slice(3).map(s=>s.name).join(', '))+'">+'+(q.suppliers.length-3)+'</span>':'')+'</div>';
const progress=q=>'<div class="cq-response"><b>'+q.received+'/'+q.invited+'</b><progress aria-label="'+q.received+' de '+q.invited+' propostas recebidas" value="'+q.received+'" max="'+(q.invited||1)+'"></progress><small>'+q.awaiting+' aguardando</small></div>';
const notice=q=>{const n=M.notice(q);return n?'<small class="cq-attention cq-attention-'+n.tone+'">● '+E(n.text)+'</small>':''};
const actions=q=>'<div class="cq-row-actions"><button data-menu="'+E(q.id)+'" aria-label="Ações de '+E(q.code)+'" aria-expanded="false" aria-controls="actions-'+E(q.id)+'">⋯</button><div id="actions-'+E(q.id)+'" class="cq-actions-menu" hidden><a href="'+href(q)+'">Abrir cotação</a><a href="'+href(q,'suppliers')+'">Ver fornecedores</a><a href="'+href(q,'compare')+'">Ver propostas / comparativo</a>'+(M.open(q)?'<button data-action="links" data-quotation="'+E(q.id)+'">Compartilhar links / lembrete</button><button data-action="deadline" data-quotation="'+E(q.id)+'">Alterar prazo</button><button data-action="close" data-quotation="'+E(q.id)+'">Encerrar cotação</button>':'')+Q.controlButtons(q)+'</div></div>';
Q.CentralList=class {
 constructor(root,onRows,onBulk,client,snapshot){this.snapshot=snapshot;this.client=client;this.root=root;this.onRows=onRows;this.onBulk=onBulk;this.page=1;this.pageSize=25;this.quick='open';this.sequence=0;this.timer=null;this.rows=[];this.data=null;
 root.innerHTML='<header class="page-h"><div><div class="crumb"><a href="cotacoes.html">← Cotações por cliente</a></div><h1>'+E(client.client_name)+'</h1><p>Cotações dos projetos deste cliente.</p></div><div class="cq-actions"><button data-action="refresh">Atualizar</button><button class="primary" data-action="new">+ Nova cotação</button></div></header><div class="cq-kpis" data-kpis></div><section class="cq-panel cq-central-panel"><label class="cq-search">Buscar projeto, cliente, oportunidade, fornecedor ou cotação<input data-filter="search" placeholder="Digite um nome ou número da cotação…" type="search"></label><details><summary>Filtros avançados</summary><div class="cq-filters">'+filters.filter(([k])=>k!=='client_name').map(([k,l])=>'<label>'+l+'<select data-filter="'+k+'"><option value="">Todos</option></select></label>').join('')+'<label>Prazo até<input type="date" data-filter="deadline"></label><label>Criadas de<input type="date" data-filter="from"></label><label>Criadas até<input type="date" data-filter="to"></label></div><button data-clear>Limpar filtros</button></details><div class="cq-actions cq-tabs">'+[['open','Em aberto'],['all','Todas'],['awaiting','Aguardando resposta'],['ready','Prontas para comparar'],['due','Vencendo hoje'],['late','Atrasadas'],['paused','Pausadas'],['closed','Encerradas'],['canceled','Canceladas'],['archived','Arquivadas'],['trash','Lixeira']].map(([k,l])=>'<button data-quick="'+k+'">'+l+'</button>').join('')+'</div><div class="cq-list-toolbar"><p data-count role="status">Carregando cotações…</p><div><label>Ordenar por<select data-sort>'+sorts.map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')+'</select></label><button data-direction aria-label="Inverter ordem" title="Ordem crescente">↑</button></div></div><div data-bulk class="cq-actions"></div><p data-status role="status" class="cq-error"></p><div data-table></div><footer class="cq-pagination"><label>Por página<select data-size><option>25</option><option>50</option><option>100</option></select></label><div><button data-page="prev" aria-label="Página anterior">← Anterior</button><span data-page-label></span><button data-page="next" aria-label="Próxima página">Próxima →</button></div></footer></section>';
 this.sort='attention';this.direction='asc';
 root.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('input',()=>{this.page=1;this.schedule(el.dataset.filter==='search'?300:0)}));
 root.querySelector('[data-sort]').onchange=e=>{this.sort=e.target.value;this.page=1;this.schedule(0)};
 root.querySelector('[data-size]').onchange=e=>{this.pageSize=Number(e.target.value);this.page=1;this.schedule(0)};
 root.addEventListener('click',e=>this.click(e));
 root.addEventListener('keydown',e=>{if(e.key==='Escape')this.closeMenus(true);if(e.target.matches('[data-row]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.href=e.target.dataset.href}});
 document.addEventListener('click',e=>{if(!e.target.closest('.cq-row-actions'))this.closeMenus()});
 }
 filterValues(){return {...Object.fromEntries([...this.root.querySelectorAll('[data-filter]')].map(el=>[el.dataset.filter,el.value.trim()])),clientKey:this.client.client_key}}
 schedule(delay){clearTimeout(this.timer);this.sequence++;this.root.querySelector('[data-table]').setAttribute('aria-busy','true');this.timer=setTimeout(()=>this.load(),delay)}
 async load(refresh=false){clearTimeout(this.timer);if(refresh)this.snapshot=null;const seq=++this.sequence,root=this.root,f=this.filterValues();root.querySelector('[data-table]').setAttribute('aria-busy','true');
 try{if(f.from&&f.to&&f.from>f.to)throw Error('A data inicial do período deve ser anterior à data final.');
 const snapshot=this.snapshot||await Q.loadClientSnapshot();if(seq!==this.sequence)return;this.snapshot=snapshot;this.client=snapshot.clients.find(c=>c.client_key===this.client.client_key)||this.client;const data=CamberQuoteClients.quotesPage(snapshot,this.client.client_key,{page:this.page,pageSize:this.pageSize,quick:this.quick,sort:this.sort,direction:this.direction,filters:f});
 this.data=data;this.rows=data.rows;this.page=data.page;this.onRows(data.rows);this.render();root.querySelector('[data-status]').textContent='';
 }catch(e){if(seq!==this.sequence)return;this.rows=[];this.onRows([]);root.querySelector('[data-table]').innerHTML='<p>Não foi possível carregar a listagem. Use Atualizar para tentar novamente.</p>';root.querySelector('[data-count]').textContent='Listagem indisponível';root.querySelector('[data-status]').textContent=e.message;this.onBulk();
 }finally{if(seq===this.sequence)root.querySelector('[data-table]').removeAttribute('aria-busy')}
 }
 render(){const {root,data}=this,k=data.kpis;
 root.querySelector('[data-kpis]').innerHTML=[['Cotações abertas',k.open,'open'],['Aguardando resposta',k.awaiting,'awaiting'],['Prontas para comparar',k.ready,'ready'],['Vencendo hoje',k.due,'due'],['Atrasadas',k.late,'late'],['Valor em cotação',Q.money(k.value),'']].map(([l,v,q])=>'<button class="cq-kpi" '+(q?'data-quick="'+q+'"':'disabled')+'><small>'+l+'</small><strong>'+v+'</strong></button>').join('');
 for(const [key] of filters){const el=root.querySelector('[data-filter="'+key+'"]');if(!el)continue;const value=el.value;el.innerHTML='<option value="">Todos</option>'+(data.facets[key]||[]).map(v=>'<option value="'+E(v)+'">'+E(key==='status'?M.labels[v]||v:v)+'</option>').join('');el.value=value;if(value&&!el.value){el.insertAdjacentHTML('beforeend','<option value="'+E(value)+'">'+E(value)+'</option>');el.value=value}}
 root.querySelector('[data-table]').innerHTML=this.rows.length?'<div class="cq-table cq-central-table"><table><thead><tr><th><input type="checkbox" data-all aria-label="Selecionar cotações desta página"></th><th>Cotação</th><th>Projeto / cliente</th><th>Oportunidade</th><th class="cq-secondary">Fornecedores</th><th>Respostas</th><th>Prazo</th><th class="cq-secondary">Valor estimado</th><th>Status</th><th>Ações</th></tr></thead><tbody>'+this.rows.map(q=>'<tr data-row tabindex="0" data-href="'+href(q)+'" aria-label="Abrir '+E(q.code)+' — '+E(q.service)+'"><td><input type="checkbox" data-check="'+E(q.id)+'" aria-label="Selecionar '+E(q.code)+'"></td><td><a href="'+href(q)+'"><b>'+E(q.code)+'</b></a></td><td class="cq-project-name"><b>'+E(q.project_name)+'</b><small>'+E(q.client_name)+'</small></td><td>'+E(q.service)+'</td><td class="cq-secondary">'+avatars(q)+'</td><td>'+progress(q)+'</td><td class="cq-date">'+date(q.expires_at)+'</td><td class="cq-secondary cq-value">'+Q.money(q.estimated_value)+'</td><td>'+badge(q)+notice(q)+'</td><td>'+actions(q)+'</td></tr>').join('')+'</tbody></table></div><div class="cq-mobile-cards">'+this.rows.map(q=>'<article class="cq-mobile-card" data-row tabindex="0" data-href="'+href(q)+'" aria-label="Abrir '+E(q.code)+'"><header><label><input type="checkbox" data-check="'+E(q.id)+'" aria-label="Selecionar '+E(q.code)+'"> '+E(q.code)+'</label>'+actions(q).replaceAll('\"actions-','\"mobile-actions-')+'</header><h2><a href="'+href(q)+'">'+E(q.service)+'</a></h2><p>'+E(q.project_name)+'</p><small>'+E(q.client_name)+'</small><strong>'+Q.money(q.estimated_value)+'</strong><div class="cq-mobile-summary">'+avatars(q)+progress(q)+'</div><p>Prazo: <b>'+date(q.expires_at)+'</b></p>'+badge(q)+notice(q)+'<a class="cq-open-link" href="'+href(q)+'">Abrir cotação →</a></article>').join('')+'</div>':'<div class="cq-empty"><h2>Nenhuma cotação encontrada</h2><p>Nenhuma cotação deste cliente nos filtros selecionados. Use Todas para consultar o histórico ou crie uma nova cotação.</p></div>';
 root.querySelector('[data-count]').textContent=data.total+(data.total===1?' cotação encontrada':' cotações encontradas');
 const pages=Math.max(1,Math.ceil(data.total/data.pageSize));root.querySelector('[data-page-label]').textContent='Página '+data.page+' de '+pages;
 root.querySelector('[data-page="prev"]').disabled=data.page<=1;root.querySelector('[data-page="next"]').disabled=data.page>=pages;
 root.querySelector('[data-direction]').disabled=this.sort==='attention';
 root.querySelectorAll('[data-quick]').forEach(el=>{el.classList.toggle('active',el.dataset.quick===this.quick);el.setAttribute('aria-pressed',String(el.dataset.quick===this.quick))});this.onBulk();
 }
 closeMenus(focus=false){this.root.querySelectorAll('[data-menu][aria-expanded="true"]').forEach(b=>{b.setAttribute('aria-expanded','false');this.root.querySelector('#'+CSS.escape(b.getAttribute('aria-controls'))).hidden=true;if(focus)b.focus()})}
 click(e){const b=e.target.closest('button'),row=e.target.closest('[data-row]');
 if(b?.dataset.menu){const panel=this.root.querySelector('#'+CSS.escape(b.getAttribute('aria-controls'))),open=panel.hidden;this.closeMenus();panel.hidden=!open;b.setAttribute('aria-expanded',String(open));if(open){const r=b.getBoundingClientRect();panel.style.left=Math.max(8,Math.min(r.right-240,innerWidth-248))+'px';panel.style.top=Math.max(8,Math.min(r.bottom+6,innerHeight-panel.offsetHeight-12))+'px';panel.querySelector('a').focus()}return}
 if(b?.dataset.quick){this.quick=b.dataset.quick;this.page=1;this.schedule(0);return}
 if(b?.hasAttribute('data-clear')){this.root.querySelectorAll('[data-filter]').forEach(el=>el.value='');this.quick='open';this.page=1;this.schedule(0);return}
 if(b?.hasAttribute('data-direction')){this.direction=this.direction==='asc'?'desc':'asc';b.textContent=this.direction==='asc'?'↑':'↓';b.title=this.direction==='asc'?'Ordem crescente':'Ordem decrescente';this.schedule(0);return}
 if(b?.dataset.page){this.page+=b.dataset.page==='next'?1:-1;this.schedule(0);return}
 if(e.target.closest('.cq-actions-menu'))this.closeMenus();
 if(row&&!e.target.closest('a,button,input,label,select,.cq-avatar-tip'))location.href=row.dataset.href;
 }
};
})();
