(function(){
'use strict';const Q=CamberQuotes,E=Q.esc,M=CamberQuoteModel;
Q.dialog=function(html){const d=document.createElement('dialog');d.className='cq-dialog';d.innerHTML=html;document.body.append(d);d.onclose=()=>d.remove();d.addEventListener('click',e=>{if(e.target.closest('[data-close]'))d.close()});d.showModal();return d;};
const item=()=>'<div class="cq-item"><label>Item<input data-title required maxlength="200"></label><label>Quantidade<input data-qty type="number" required value="1" min="0.01" max="100000" step="0.01"></label><label>Unidade<input data-unit required value="un" maxlength="30"></label><button type="button" class="cq-x" data-remove-item aria-label="Remover item">×</button></div>';
const room=()=>'<div class="cq-room"><div class="cq-row"><label>Cômodo / grupo<input data-room required maxlength="100" placeholder="Ex.: Cozinha"></label><button type="button" class="cq-x" data-remove-room aria-label="Remover cômodo">×</button></div><div data-items>'+item()+'</div><button type="button" data-add-item>+ Item</button></div>';
Q.wizard=async function({projectId='',opportunityId='',newOpportunity=false,lockContext=false}={}){
 const c=await Q.api('catalog'),qid=crypto.randomUUID(),oid=String(Date.now());let step=0,working=false,result=null,uploads=new Set();
 const d=Q.dialog(`<div class="cq-row"><h2>${newOpportunity?'Nova oportunidade':'Nova cotação'}</h2><button class="cq-x" data-close aria-label="Fechar">×</button></div><div data-progress></div><form><fieldset data-step><label>Projeto<select name="project" required><option value="">Selecione</option>${c.projects.map(p=>`<option value="${E(p.id)}">${E(p.nome)}</option>`).join('')}</select></label>${newOpportunity?'<label>Serviço / oportunidade<input name="service" required maxlength="150" list="cq-services"></label><datalist id="cq-services"><option>Marcenaria</option><option>Iluminação</option><option>Vidraçaria</option><option>Pisos</option></datalist><label>Responsável<select name="responsible">'+c.responsibles.map(n=>'<option>'+E(n)+'</option>').join('')+'</select></label>':'<label>Oportunidade<select name="opportunity" required></select></label>'}<div class="cq-two"><label>Prazo para responder<input type="date" name="deadline" required value="${new Date(Date.now()+14*86400000).toISOString().slice(0,10)}"></label><label>Valor estimado (R$)<input type="number" name="estimate" min="0" max="1000000000" step="0.01" value="0" required></label></div></fieldset><fieldset data-step hidden><label>Como definir o pedido<select name="mode"><option value="standard">Modelo padrão</option><option value="custom">Escrever meu pedido</option></select></label><label>Título do pedido<input name="title" required maxlength="150"></label><label>O que deve ser orçado<textarea name="description" required maxlength="3000"></textarea></label><div data-rooms>${room()}</div><button type="button" data-add-room>+ Adicionar cômodo</button><label>Anexar o projeto<input type="file" name="files" multiple accept=".pdf,.png,.jpg,.jpeg,.dwg,.dxf,.zip"></label><small>Disponível nos dois modelos. Até 10 arquivos de 25 MB cada.</small></fieldset><fieldset data-step hidden><h3>Selecionar fornecedores participantes</h3><p class="cq-muted">Escolha os fornecedores que receberão a solicitação de cotação para esta oportunidade.</p><label>Buscar fornecedor<input name="search" placeholder="Nome, cidade ou estado"></label><div data-suppliers></div><a href="fornecedor.html" target="_blank" rel="noopener">+ Cadastrar fornecedor</a> <button type="button" data-refresh>Atualizar cadastro</button></fieldset><fieldset data-step hidden><h3>Revisar e criar</h3><div data-review></div><p>Será criado um link individual para cada fornecedor. Compartilhe os links manualmente. Nenhum e-mail será enviado.</p></fieldset><p class="cq-error" role="alert"></p><p data-saving role="status"></p><div class="cq-row"><button type="button" data-prev>Voltar</button><button type="button" class="primary" data-next>Continuar</button></div></form>`);
 const form=d.querySelector('form'),f=form.elements,sets=[...d.querySelectorAll('[data-step]')];
 function opps(){if(newOpportunity)return;f.opportunity.innerHTML='<option value="">Selecione</option>'+c.opportunities.filter(x=>String(x.projectId)===f.project.value).map(x=>`<option value="${E(x.opportunity.id)}">${E(x.opportunity.serv)} · ${E(x.opportunity.titulo||'')}</option>`).join('');}
 f.project.value=String(projectId);opps();if(!newOpportunity)f.opportunity.value=String(opportunityId);if(lockContext&&!newOpportunity){f.project.disabled=true;f.opportunity.disabled=true}
 const service=()=>newOpportunity?f.service.value:c.opportunities.find(x=>String(x.projectId)===f.project.value&&String(x.opportunity.id)===f.opportunity.value)?.opportunity.serv||'';
 const selected=new Set();
 function selectedList(){let aside=d.querySelector('[data-selected-suppliers]');if(!aside){const list=d.querySelector('[data-suppliers]'),grid=document.createElement('div');grid.className='cq-supplier-picker';list.before(grid);grid.append(list);aside=document.createElement('aside');aside.dataset.selectedSuppliers='';grid.append(aside)}aside.innerHTML='<h3>Fornecedores selecionados ('+selected.size+')</h3>'+c.suppliers.filter(s=>selected.has(String(s.id))).map(s=>'<div class="cq-row">'+Q.avatar(s.nome)+'<div><b>'+E(s.nome)+'</b><small>'+E([s.cidade,s.uf].filter(Boolean).join(' · '))+'</small></div><button type="button" class="cq-x" data-unpick="'+E(s.id)+'" aria-label="Remover '+E(s.nome)+'">×</button></div>').join('')+(selected.size?'':'<p>Marque os fornecedores ao lado.</p>');}
 function suppliers(){d.querySelector('[data-suppliers]').innerHTML=c.suppliers.filter(s=>M.eligible(s,service())).map(s=>`<label class="cq-pick" data-name="${E(M.norm([s.nome,s.cidade,s.uf].join(' ')))}"><input type="checkbox" data-supplier="${E(s.id)}" ${selected.has(String(s.id))?'checked':''}> ${Q.avatar(s.nome)}<span class="cq-supplier-info"><b>${E(s.nome)}</b><small>${E([s.cidade,s.uf].filter(Boolean).join(' · '))}</small><small>${E((Array.isArray(s.categorias)?s.categorias:[s.categoria]).filter(Boolean).join(', '))}</small></span></label>`).join('')||'<p>Nenhum fornecedor ativo com este serviço cadastrado.</p>';f.search.dispatchEvent(new Event('input'));selectedList();}
 f.project.onchange=()=>{opps();selected.clear()};if(newOpportunity)f.service.onchange=()=>selected.clear();else f.opportunity.onchange=()=>selected.clear();
 f.search.oninput=()=>d.querySelectorAll('[data-name]').forEach(n=>n.hidden=!n.dataset.name.includes(M.norm(f.search.value)));
 const items=()=>[...d.querySelectorAll('.cq-room')].flatMap((r,ri)=>[...r.querySelectorAll('.cq-item')].map((i,ii)=>({id:`${ri}-${ii}`,room:r.querySelector('[data-room]').value.trim(),title:i.querySelector('[data-title]').value.trim(),quantity:Number(i.querySelector('[data-qty]').value),unit:i.querySelector('[data-unit]').value.trim()})));
 function render(){sets.forEach((s,i)=>s.hidden=i!==step);d.querySelector('[data-progress]').innerHTML=Q.stepper(['Dados gerais','Produtos e escopo','Fornecedores','Revisar e criar'],step);d.querySelector('[data-prev]').hidden=step===0;d.querySelector('[data-next]').textContent=step===3?(result?'Tentar anexos restantes':'Criar cotação e links'):'Continuar';if(step===2)suppliers();if(step===3)d.querySelector('[data-review]').innerHTML=`<p><b>${E(f.title.value)}</b> · ${E(service())}</p><p>${items().length} itens · ${selected.size} fornecedores · ${f.files.files.length} anexos</p><p>Estimativa: ${Q.money(f.estimate.value)} · prazo: ${E(f.deadline.value.split('-').reverse().join('/'))}</p><p>${c.suppliers.filter(s=>selected.has(String(s.id))).map(s=>E(s.nome)).join(' · ')}</p>`;}
 form.onsubmit=e=>e.preventDefault();
 d.addEventListener('cancel',e=>{if(working)e.preventDefault()});
 d.addEventListener('change',e=>{if(e.target.dataset.supplier){e.target.checked?selected.add(e.target.dataset.supplier):selected.delete(e.target.dataset.supplier);selectedList()}});
 d.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||working)return;try{
  if(b.hasAttribute('data-unpick')){selected.delete(b.dataset.unpick);suppliers();}
  if(b.hasAttribute('data-add-room'))d.querySelector('[data-rooms]').insertAdjacentHTML('beforeend',room());
  if(b.hasAttribute('data-add-item'))b.closest('.cq-room').querySelector('[data-items]').insertAdjacentHTML('beforeend',item());
  if(b.hasAttribute('data-remove-room'))b.closest('.cq-room').remove();if(b.hasAttribute('data-remove-item'))b.closest('.cq-item').remove();
  if(b.hasAttribute('data-refresh')){c.suppliers=(await Q.api('catalog')).suppliers;suppliers();}
  if(b.hasAttribute('data-prev')){step--;render()}
  if(!b.hasAttribute('data-next'))return;
  d.querySelector('.cq-error').textContent='';
  for(const el of sets[step].querySelectorAll('input,textarea,select'))if(!el.checkValidity()){el.reportValidity();return}
  if(step===0){if(!f.title.value)f.title.value='Orçamento de '+service();if(!f.description.value)f.description.value='Orçar os itens abaixo conforme o projeto anexo. Informar materiais, valores unitários e condições de fornecimento.';}
  if(step===1&&(!items().length||items().length>100))throw Error('Adicione de 1 a 100 itens.');
  if(step===2&&!selected.size)throw Error('Selecione ao menos um fornecedor.');
  if(step<3){step++;render();return}
  const files=[...f.files.files];if(files.length>10||files.some(x=>!x.size||x.size>26214400||!/\.(pdf|png|jpe?g|dwg|dxf|zip)$/i.test(x.name)))throw Error('Confira os anexos: até 10 arquivos válidos de 25 MB.');
  working=true;d.querySelectorAll('button').forEach(x=>x.disabled=true);d.querySelector('[data-saving]').textContent='Criando cotação…';
  if(!result)result=await Q.api(newOpportunity?'create_opportunity':'new_quotation',{quotationId:qid,projectId:f.project.value,opportunityId:newOpportunity?oid:f.opportunity.value,service:service(),responsible:f.responsible?.value||'',estimatedValue:Number(f.estimate.value),expiresAt:f.deadline.value+'T23:59:59-03:00',supplierIds:[...selected],specification:{mode:f.mode.value,title:f.title.value,description:f.description.value,items:items()}});
  form.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);
  const detail=await Q.api('detail',{quotationId:qid});for(const r of detail.requests)for(let i=0;i<files.length;i++){const key=r.id+':'+i;if(uploads.has(key))continue;d.querySelector('[data-saving]').textContent='Anexando projeto · '+r.supplier_name;await Q.api('upload',{id:r.id,fileId:await fileId(r.id,i)},files[i]);uploads.add(key);}
  if(window.CamberCloud?.atualizarOportunidades)await CamberCloud.atualizarOportunidades(f.project.value);
  location.href='cotacoes.html?id='+encodeURIComponent(qid);
 }catch(err){d.querySelector('.cq-error').textContent=err.message;d.querySelector('[data-saving]').textContent=result?'A cotação está salva. Tente novamente para concluir os anexos.':'';}finally{working=false;d.querySelectorAll('button').forEach(x=>x.disabled=false);if(result){d.querySelector('[data-prev]').disabled=true;d.querySelector('[data-next]').textContent='Concluir anexos';}}});
 const uploadIds=new Map();async function fileId(r,i){const key=r+':'+i;if(!uploadIds.has(key))uploadIds.set(key,crypto.randomUUID());return uploadIds.get(key)}
 render();
};
})();
