(function(){
  'use strict';
  const Q=CamberQuotes,E=Q.esc,M=window.CamberQuoteModel;
  const css=document.createElement('link');css.rel='stylesheet';css.href='cotacoes-layout.css?v=1';document.body.append(css);
  Q.avatar=name=>'<span class="cq-avatar" aria-hidden="true">'+E(String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join(''))+'</span>';
  Q.stepper=(labels,current)=>'<ol class="cq-stepper" aria-label="Etapas">'+labels.map((label,i)=>'<li class="'+(i<current?'complete':i===current?'current':'')+'" '+(i===current?'aria-current="step"':'')+'><span>'+(i<current?'✓':i+1)+'</span><b>'+E(label)+'</b></li>').join('')+'</ol>';
  const date=x=>x?new Date(x.includes('T')?x:x+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
  Q.quoteAside=d=>{const q=d.quotation;return '<aside class="cq-detail-aside"><section class="cq-panel"><h3>Status da cotação</h3><p>'+q.received+' de '+q.invited+' propostas recebidas</p><progress value="'+q.received+'" max="'+(q.invited||1)+'"></progress><small>Prazo para recebimento</small><b>'+date(q.expires_at)+'</b></section><section class="cq-panel"><h3>Resumo da oportunidade</h3><small>Valor estimado</small><strong>'+Q.money(q.estimated_value)+'</strong><small>Categoria</small><b>'+E(q.service)+'</b><small>Descrição</small><p>'+E(q.specification.description)+'</p></section><section class="cq-panel"><h3>Fornecedores participantes</h3><p>'+M.counts(q)+'</p>'+d.requests.map(r=>'<div class="cq-person">'+Q.avatar(r.supplier_name)+'<div><b>'+E(r.supplier_name)+'</b><small class="'+(r.response?'cq-text-green':'')+'">'+E(M.labels[r.status]||r.status)+'</small></div></div>').join('')+(M.open(q)?'<button data-action="add-participants">+ Adicionar fornecedor</button>':'')+'</section></aside>'};
  Q.comparisonHTML=d=>{const q=d.quotation,rs=d.requests,received=rs.filter(r=>M.currentResponse(r)&&M.savings(r.response.total,r.response.total)),max=received.length?Math.max(...received.map(r=>Number(r.response.total))):null,min=received.length?Math.min(...received.map(r=>Number(r.response.total))):null;
    const economy=r=>{if(!received.includes(r))return 'Não comparável';if(received.length<2)return 'Aguardando outra proposta';const s=M.savings(r.response.total,max);if(min===max)return 'Sem diferença';if(!s.amount)return 'Maior valor · referência';return '<b>'+Q.money(s.amount)+'</b><small>'+s.percent.toLocaleString('pt-BR',{maximumFractionDigits:2})+'% de economia em relação ao maior valor</small>';};
    const cells=(title,fn,cls='')=>'<tr class="'+cls+'"><th colspan="2" scope="row">'+title+'</th>'+rs.map(r=>'<td>'+(r.response?fn(r):'—')+'</td>').join('')+'</tr>';
    return '<h2>Comparativo de propostas</h2><div class="cq-table cq-comparison"><table><thead><tr><th>Item</th><th>Qtd.</th>'+rs.map(r=>'<th>'+E(r.supplier_name)+'<small class="'+(r.response?'cq-text-green':'cq-text-amber')+'">● '+E(M.labels[r.status]||r.status)+'</small></th>').join('')+'</tr></thead><tbody>'+q.specification.items.map(i=>'<tr><td>'+E(i.room?i.room+' · ':'')+E(i.title)+'</td><td>'+E(i.quantity+' '+i.unit)+'</td>'+rs.map(r=>{const x=r.response?.items.find(x=>x.id===i.id);return '<td>'+(x?Q.money(x.value):'—')+'</td>'}).join('')+'</tr>').join('')+
      cells('Valor dos produtos',r=>'<b>'+Q.money(r.response.subtotal)+'</b>')+cells('Desconto',r=>r.response.discountPercent+'% · '+Q.money(r.response.discount))+cells('Frete',r=>Q.money(r.response.freight))+cells('Montagem',r=>Q.money(r.response.assembly))+cells('Valor final',r=>'<b>'+Q.money(r.response.total)+'</b>','cq-final-row')+
      cells('Economia R$ / %',economy)+
      cells('Prazo de entrega',r=>r.response.days+' dias')+cells('Contagem do prazo',r=>E(r.response.basis||'—'))+cells('Condição de pagamento',r=>E(r.response.payment))+cells('Entrega prevista',r=>date(r.response.delivery))+cells('Montagem',r=>date(r.response.start)+' a '+date(r.response.end))+
      (d.financial?cells('RT Camber',r=>{const f=d.financial.find(f=>f.proposalId===r.proposal_id);return f?Q.money(CamberRemuneration.calculate(f,r.response).rt):'Não cadastrada'}):'')+
      (d.financial?['cost','markup','client','earned','received','pending'].map((key,i)=>cells(['Valor do fornecedor','Acréscimo do escritório','Preço ao cliente','Remuneração total prevista','Remuneração recebida','Saldo a receber'][i],r=>{const f=d.financial.find(f=>String(f.proposalId)===String(r.proposal_id));return f?Q.money(CamberRemuneration.calculate(f,r.response)[key]):'Não cadastrada'})).join(''):'')+
      '<tr class="cq-status-row"><th colspan="2">Status / ações</th>'+rs.map(r=>'<td><small>'+E(M.labels[r.status]||r.status)+'</small>'+(d.financial?'<button data-request="'+r.id+'" data-do="remuneration">Remuneração</button>':'')+(r.response?'<button data-request="'+r.id+'" data-do="response">Ver detalhes</button>':'')+(M.open(q)&&r.status==='SUBMITTED'?'<button class="primary" data-request="'+r.id+'" data-do="select">Selecionar</button>':'')+'</td>').join('')+'</tr></tbody></table></div><p class="cq-muted">Compare também materiais, exclusões e condições. Os valores internos da Camber ficam restritos ao escritório.</p>';
  };
})();
