(async function(){
'use strict';const Q=CamberQuotes,E=Q.esc,M=CamberQuoteModel,root=document.getElementById('cq-main'),params=new URLSearchParams(location.search),id=params.get('id'),clientKey=params.get('client'),purchases=document.getElementById('app').dataset.page==='compras';let rows=[],detail,tab=params.get('tab')||'overview',selected=new Set(),quick='all',busy=false,catalog,centralView,clientInfo;
const badge=st=>'<span class="cq-badge '+(['READY','CLOSED','SELECTED'].includes(st)?'good':['EXPIRED','DISQUALIFIED'].includes(st)?'bad':['DRAFT','CANCELED','NOT_SELECTED'].includes(st)?'neutral':'wait')+'">'+E(M.labels[st]||st)+'</span>';
const date=x=>x?new Date(x).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const table=(headers,body)=>'<div class="cq-table"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table></div>';
const cells=arr=>'<tr>'+arr.map(x=>'<td>'+x+'</td>').join('')+'</tr>';
const kpi=(label,value,key)=>'<button class="cq-kpi" '+(key?'data-quick="'+key+'"':'disabled')+'><small>'+label+'</small><strong>'+value+'</strong></button>';
const status=msg=>{const el=root.querySelector('[data-status]');if(el)el.textContent=msg};
const link=r=>location.origin+location.pathname.replace(/[^/]*$/,'responder-proposta.html')+'#token='+r.token;
async function run(fn){if(busy)return;busy=true;try{await fn()}catch(e){status(e.message);if(!root.querySelector('[data-status]'))alert(e.message)}finally{busy=false}}
function exportRows(data){const safe=v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const csv=[['Cotação','Projeto','Oportunidade','Convidados','Respostas','Aguardando','Prazo','Estimativa','Status'],...data.map(q=>[q.code,q.project_name,q.service,q.invited,q.received,q.awaiting,date(q.expires_at),q.estimated_value,M.labels[q.status]])].map(a=>a.map(safe).join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));a.download='cotacoes.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bulk(){const s=rows.filter(q=>selected.has(q.id)),compatible=s.length&&s.every(M.open);root.querySelector('[data-bulk]').innerHTML=s.length?'<b>'+s.length+' selecionada(s) nesta página</b> <button data-action="export">Exportar</button> '+(compatible?'<button data-action="links">Compartilhar links / lembrete</button> <button data-action="deadline">Alterar prazo</button> <button data-action="close">Encerrar</button>':''):'';}
async function central(){
 if(!centralView){
  if(clientKey){const snapshot=await Q.loadClientSnapshot();clientInfo=snapshot.clients.find(c=>c.client_key===clientKey);if(!clientInfo)throw Error('Cliente não encontrado nas cotações. Volte a Cotações pelo menu.');centralView=new Q.CentralList(root,data=>{rows=data;selected.clear()},bulk,clientInfo,snapshot);await centralView.load();return;}
  else centralView=new Q.ClientDirectory(root);
 }
 await centralView.load(true);if(clientKey)clientInfo=centralView.client;
}
async function newQuotation(){
 await Q.wizard({checkExisting:true,projectIds:clientInfo?.projects.map(p=>p.id),projectId:clientInfo?.projects.length===1?clientInfo.projects[0].id:''});
}
async function links(quotes,requestId){const requests=(await Promise.all(quotes.map(q=>Q.api('detail',{quotationId:q.id})))).flatMap(d=>d.requests.filter(r=>(!requestId||r.id===requestId)&&r.active&&Date.parse(r.expires_at)>Date.now()&&!['DECLINED','DISQUALIFIED','NOT_SELECTED'].includes(r.status)));const d=Q.dialog('<div class="cq-row"><h2>Enviar cotação</h2><button data-close class="cq-x" aria-label="Fechar">×</button></div><p>Confira a cotação e os anexos. Copie o link individual e envie ao fornecedor quando desejar. O sistema não envia mensagens automaticamente.</p>'+requests.map((r,i)=>`<label>${E(r.supplier_name)} · ${E(r.project_name)}<input readonly value="${E(link(r))}"></label><button data-copy="${i}">Copiar link</button>`).join('')+'<p data-msg role="status"></p>');d.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(link(requests[Number(b.dataset.copy)]));d.querySelector('[data-msg]').textContent='Link copiado.'}catch{d.querySelector('[data-msg]').textContent='Selecione o endereço e copie.'}});}
async function changeDeadline(quotes){const d=Q.dialog('<h2>Alterar prazo</h2><form><label>Novo prazo<input type="date" name="date" required></label><p class="cq-error"></p><button type="button" data-close>Cancelar</button> <button class="primary">Salvar prazo</button></form>');d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=d.querySelector('.primary');b.disabled=true;try{for(const q of quotes)await Q.api('deadline',{quotationId:q.id,expiresAt:d.querySelector('input').value+'T23:59:59-03:00'});d.close();await reload()}catch(err){d.querySelector('.cq-error').textContent=err.message;b.disabled=false}};}
async function loadDetail(){detail=await Q.api('detail',{quotationId:id});const {catalog,clients}=await Q.loadClientCatalog();detail.quotation=CamberQuoteClients.build(catalog.projects,clients,[detail.quotation]).quotes[0];if(tab==='compare')await Q.api('reviewed',{quotationId:id});renderDetail()}
function tabs(){return [['overview','Visão geral'],['items','Itens'],['suppliers','Fornecedores'],['compare','Comparativo'],['negotiation','Negociação'],['documents','Documentos'],['history','Histórico']].map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${l}</button>`).join('')}
function renderDetail(){const q=detail.quotation;root.innerHTML=`<div class="crumb"><a href="cotacoes.html">Cotações por cliente</a> › <a href="cotacoes.html?client=${encodeURIComponent(q.client_key)}">${E(q.client_name)}</a> › ${E(q.service)}</div><header class="page-h cq-detail-header"><div><div class="crumb">${E(q.code)}</div><h1>${E(q.service)}</h1><p>Projeto: ${E(q.project_name)}</p><p>Responsável: ${E(q.responsible||'Não definido')} · ${badge(q.status)}</p></div><div class="cq-actions"><a href="projeto.html?id=${encodeURIComponent(q.project_id)}&area=oportunidades&opp=${encodeURIComponent(q.opportunity_id)}">Abrir oportunidade</a><button data-action="refresh">Atualizar</button><button data-action="print-comparison">Imprimir comparação</button>${Q.controlButtons(q)}${q.selected_request_id?'<button class="primary" data-action="purchase">'+(detail.purchase?'Abrir pedido de compra':'Gerar pedido de compra')+'</button>':M.open(q)?'<button data-action="links">Enviar cotação</button><button data-action="deadline">Alterar prazo</button><button data-action="close">Encerrar</button>':''}</div></header><nav class="cq-actions cq-tabs" aria-label="Áreas da cotação">${tabs()}</nav><p data-status role="status" class="cq-error"></p><div class="cq-detail-grid"><section class="cq-panel" data-content></section>${Q.quoteAside(detail)}</div>`;content();}
function content(){const q=detail.quotation,rs=detail.requests,el=root.querySelector('[data-content]');if(tab==='compare'){el.innerHTML=Q.comparisonHTML(detail);return;}
 if(tab==='overview'){el.innerHTML='<div class="cq-kpis">'+kpi('Valor estimado',Q.money(q.estimated_value))+kpi('Fornecedores convidados',q.invited)+kpi('Propostas recebidas',q.received)+kpi('Aguardando',q.awaiting)+kpi('Menor proposta',q.lowest===null?'—':Q.money(q.lowest))+kpi('Prazo',date(q.expires_at))+'</div><h2>Andamento da cotação</h2><ol class="cq-timeline">'+[['Cotação criada',true],['Fornecedores convidados',q.invited>0],['Propostas recebidas',q.received>0],['Comparação',!!q.reviewed_at],['Negociação',rs.some(r=>r.revision>1)],['Fornecedor selecionado',!!q.selected_request_id],['Pedido de compra',!!detail.purchase]].map(([l,done])=>'<li class="'+(done?'done':'')+'">'+(done?'✓ ':'○ ')+l+'</li>').join('')+'</ol><p><b>'+E(q.specification.title)+'</b></p><p style="white-space:pre-wrap">'+E(q.specification.description)+'</p>';}
 if(tab==='items')el.innerHTML=table(['Cômodo','Item','Quantidade','Unidade'],q.specification.items.map(i=>cells([E(i.room),E(i.title),i.quantity,E(i.unit)])).join(''));
 if(tab==='suppliers')el.innerHTML='<div class="cq-row"><h2>Participantes</h2>'+(M.open(q)?'<button data-action="add-participants">+ Adicionar fornecedores</button>':'')+'</div>'+table(['Fornecedor','Status','Visualização','Última resposta','Ações'],rs.map(r=>cells([E(r.supplier_name),badge(r.active?r.status:'DRAFT'),date(r.viewed_at),date(r.responded_at),`<button data-request="${r.id}" data-do="link">Link</button> ${detail.financial?`<button data-request="${r.id}" data-do="remuneration">Remuneração</button>`:''} ${r.response?`<button data-request="${r.id}" data-do="response">Valores</button>`:''} ${M.open(q)&&r.active?`<button data-request="${r.id}" data-do="disqualify">Desclassificar</button>`:''}`])).join(''));
 if(tab==='negotiation')el.innerHTML='<h2>Negociação por rodadas</h2><p>Selecione as propostas recebidas para pedir revisão. As versões anteriores são preservadas.</p>'+rs.map(r=>{const vs=detail.versions.filter(v=>v.request_id===r.id),first=vs[0],last=vs.at(-1),diff=first&&last?M.delta(first.response.total,last.response.total):null;return '<article class="cq-room">'+(M.open(q)&&r.status==='SUBMITTED'?`<label><input type="checkbox" data-negotiate="${r.id}"> <b>${E(r.supplier_name)}</b></label>`:'<b>'+E(r.supplier_name)+'</b>')+' '+badge(r.status)+(diff?'<p>Original: '+Q.money(first.response.total)+' · Última: '+Q.money(last.response.total)+'<br>Diferença: '+Q.money(diff.amount)+' · '+diff.percent.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%</p>':'<p>Aguardando primeira proposta.</p>')+vs.map(v=>`<button data-version="${v.id}">Rodada ${v.version} · ${Q.money(v.response.total)}</button>`).join(' ')+'</article>'}).join('')+(M.open(q)?'<label>O que revisar<textarea id="negotiation-note" maxlength="3000" placeholder="Ex.: Rever valores e reduzir o prazo de entrega."></textarea></label><button class="primary" data-action="negotiate">Solicitar revisão de proposta</button><p>Após salvar, compartilhe novamente os links. Não há envio automático de e-mail.</p>':'');
 if(tab==='documents'){el.innerHTML='<h2>Documentos por fornecedor</h2><p>Projetos enviados e PDFs das propostas. Os links de download duram cinco minutos.</p>'+rs.map(r=>`<article class="cq-room"><b>${E(r.supplier_name)}</b><button data-request="${r.id}" data-do="files">Abrir documentos</button></article>`).join('');}
 if(tab==='history')el.innerHTML='<h2>Histórico</h2>'+detail.events.map(e=>'<article class="cq-room"><b>'+E(e.event)+'</b><small>'+E(e.supplier||'')+' · '+E(e.actor||'Fornecedor / sistema')+' · '+new Date(e.at).toLocaleString('pt-BR')+'</small></article>').join('');
}
async function pick(){const q=detail.quotation;if(!catalog)catalog=await Q.api('catalog');const fs=catalog.suppliers.filter(f=>M.eligible(f,q.service)&&!detail.requests.some(r=>r.supplier_id===String(f.id)));const d=Q.dialog('<h2>Adicionar fornecedores</h2><p>Serviço: '+E(q.service)+'</p>'+fs.map(f=>`<label class="cq-pick"><input type="checkbox" value="${E(f.id)}"> ${E(f.nome)}</label>`).join('')+'<p class="cq-error"></p><button data-close>Cancelar</button> <button class="primary">Adicionar e gerar links</button>');d.querySelector('.primary').onclick=async e=>{try{e.target.disabled=true;const supplierIds=[...d.querySelectorAll('input:checked')].map(i=>i.value);if(!supplierIds.length)throw Error('Selecione um fornecedor.');await Q.api('add_participants',{quotationId:q.id,projectId:q.project_id,opportunityId:q.opportunity_id,supplierIds});d.close();await loadDetail()}catch(err){d.querySelector('.cq-error').textContent=err.message;e.target.disabled=false}};}
async function selectSupplier(r){const d=Q.dialog('<h2>Confirmar seleção</h2><p><b>'+E(r.supplier_name)+'</b><br>Valor: '+Q.money(r.response.total)+'<br>Prazo: '+r.response.days+' dias<br>Pagamento: '+E(r.response.payment)+'</p><p>Os demais participantes ficarão como não selecionados. As propostas serão preservadas.</p><p class="cq-error"></p><button data-close>Cancelar</button> <button class="primary">Confirmar fornecedor</button>');d.querySelector('.primary').onclick=async e=>{try{e.target.disabled=true;await Q.api('select_supplier',{quotationId:id,requestId:r.id});d.close();await loadDetail()}catch(err){d.querySelector('.cq-error').textContent=err.message;e.target.disabled=false}};}
async function purchaseList(){rows=await Q.api('purchases');root.innerHTML='<header class="page-h"><div><h1>Compras</h1><p>Pedidos gerados a partir da proposta selecionada. A emissão não autoriza pagamento ao fornecedor.</p></div><button data-action="refresh">Atualizar</button></header><p data-status class="cq-error" role="status"></p><section class="cq-panel">'+table(['Pedido','Projeto / oportunidade','Fornecedor','Valor','Entrega prevista','Situação',''],rows.map(p=>cells([E(p.code),E(p.project_name)+'<small>'+E(p.service)+'</small>',E(p.supplier_name),Q.money(p.response.total),E(p.expected_delivery||'—'),'Aguardando aprovação',`<button data-purchase="${p.id}">Abrir pedido</button>`])).join('')||'<tr><td colspan="7">Nenhum pedido. Escolha um fornecedor em Cotações para gerar a compra.</td></tr>')+'</section>';if(id){const p=rows.find(p=>p.id===id);if(p)purchaseDetail(p)}}
function purchaseDetail(p){const d=Q.dialog('<div class="cq-row"><h2>'+E(p.code)+'</h2><button data-close class="cq-x" aria-label="Fechar">×</button></div><p>'+E(p.project_name)+' · '+E(p.service)+'<br><b>'+E(p.supplier_name)+'</b></p><p>Aguardando aprovação · Criado em '+date(p.created_at)+'</p>'+Q.responseHTML(p.response)+'<div class="cq-actions"><a href="cotacoes.html?id='+p.quotation_id+'">Cotação de origem</a><button data-docs>Documentos</button><button data-print>Imprimir / salvar PDF</button></div>');d.querySelector('[data-print]').onclick=()=>window.print();d.querySelector('[data-docs]').onclick=()=>docs(p.request_id);}
async function docs(requestId){const data=await Q.api('files',{id:requestId});Q.dialog('<div class="cq-row"><h2>Documentos</h2><button data-close class="cq-x" aria-label="Fechar">×</button></div>'+data.files.map(f=>'<p><a href="'+E(f.url)+'" target="_blank" rel="noopener">'+E(f.name)+' ↓</a></p>').join('')+(data.files.length?'':'<p>Nenhum documento anexado.</p>'));}
async function reload(){if(purchases)await purchaseList();else if(id)await loadDetail();else await central()}
root.addEventListener('change',e=>{if(e.target.dataset.check){e.target.checked?selected.add(e.target.dataset.check):selected.delete(e.target.dataset.check)}if(e.target.hasAttribute('data-all')){rows.forEach(q=>e.target.checked?selected.add(q.id):selected.delete(q.id))}if(e.target.dataset.check||e.target.hasAttribute('data-all')){root.querySelectorAll('[data-check]').forEach(x=>x.checked=selected.has(x.dataset.check));const all=root.querySelector('[data-all]');if(all){all.checked=rows.length>0&&selected.size===rows.length;all.indeterminate=selected.size>0&&selected.size<rows.length}bulk()}});
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.quick||b.dataset.menu||b.hasAttribute('data-page')||b.hasAttribute('data-clear')||b.hasAttribute('data-direction'))return;run(async()=>{
 if(b.dataset.tab){tab=b.dataset.tab;if(tab==='compare')await Q.api('reviewed',{quotationId:id});renderDetail();return}
 if(b.dataset.version){const v=detail.versions.find(v=>v.id===b.dataset.version);Q.details(v.response,'Proposta · Rodada '+v.version);return}
 if(b.dataset.purchase){purchaseDetail(rows.find(p=>p.id===b.dataset.purchase));return}
 if(b.dataset.request){const r=detail.requests.find(r=>r.id===b.dataset.request);if(b.dataset.do==='remuneration')await Q.editRemuneration({projectId:detail.quotation.project_id,opportunityId:detail.quotation.opportunity_id,proposalId:r.proposal_id},loadDetail);if(b.dataset.do==='response')Q.details(r.response,r.supplier_name);if(b.dataset.do==='select')await selectSupplier(r);if(b.dataset.do==='link')await links([detail.quotation],r.id);if(b.dataset.do==='files')await docs(r.id);if(b.dataset.do==='disqualify'&&confirm('Desclassificar '+r.supplier_name+'?')){await Q.api('disqualify',{id:r.id});await loadDetail()}return}
 const a=b.dataset.action,qs=id?[detail.quotation]:rows.filter(q=>b.dataset.quotation?q.id===b.dataset.quotation:selected.has(q.id));if(a==='control'){await Q.controlDialog(qs[0],b.dataset.control,reload);return}if(a==='print-comparison')Q.printComparison(detail);if(a==='refresh')await reload();if(a==='new')await newQuotation();if(a==='export')exportRows(qs);if(a==='links')await links(qs);if(a==='deadline')await changeDeadline(qs);if(a==='close'&&confirm('Encerrar '+qs.length+' cotação(ões)? Os links deixarão de aceitar respostas.')){for(const q of qs)await Q.api('workflow',{quotationId:q.id,state:'CLOSED'});selected.clear();await reload()}
 if(a==='add-participants')await pick();if(a==='negotiate'){const requestIds=[...root.querySelectorAll('[data-negotiate]:checked')].map(i=>i.dataset.negotiate);await Q.api('negotiate',{quotationId:id,requestIds,note:document.getElementById('negotiation-note').value});await loadDetail();await links([detail.quotation])}
 if(a==='purchase'){const p=detail.purchase?{id:detail.purchase}:await Q.api('purchase',{quotationId:id});location.href='compras.html?id='+p.id}
});});
try{await Q.ready();await reload();if(id&&params.get('send')==='1'&&!purchases&&M.open(detail.quotation))await links([detail.quotation]);if(id&&params.get('add')==='1'&&!purchases)await pick()}catch(e){root.innerHTML='<h1>'+(purchases?'Compras':'Cotações')+'</h1><p class="cq-error">'+E(e.message)+'</p><button onclick="location.reload()">Tentar novamente</button>'}
})();
