(() => {
 'use strict';
 const uid=()=>globalThis.crypto?.randomUUID?.() || 'demo-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
 const KEY='camber-referral-demo-v1', statuses=['Novo lead','Contato feito','Reunião agendada','Proposta enviada','Fechado','Perdido'];
 const partners=[{id:'ana-demo',name:'Ana Silva',agency:'Imobiliária Horizonte'},{id:'pedro-demo',name:'Pedro Costa',agency:'Imobiliária Horizonte'},{id:'luiza-demo',name:'Luiza Lima',agency:'Imobiliária Jardins'}];
 const date=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
 const fmt=d=>d?d.split('-').reverse().join('/'):'—', money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const seed=()=>['Cliente Exemplo A','Cliente Exemplo B','Cliente Exemplo C','Cliente Exemplo D','Cliente Exemplo E','Cliente Exemplo F'].map((name,i)=>({id:uid(),name,phone:`1190000000${i}`,partner:partners[i%3].id,status:statuses[i],owner:i%2?'Bruno · Comercial':'Marina · Comercial',action:['Fazer primeiro contato','Confirmar interesse','Confirmar reunião','Retornar proposta','Acompanhar entrega','Sem ação pendente'][i],due:date(i<2?-1:i),value:[18000,32000,45000,60000,50000,25000][i],payment:'Prevista',history:['Registro fictício criado para demonstração.']}));
 let items;try{const raw=JSON.parse(localStorage.getItem(KEY));items=Array.isArray(raw)&&raw.every(x=>x&&typeof x.name==='string'&&Array.isArray(x.history)&&partners.some(p=>p.id===x.partner)&&statuses.includes(x.status))?raw:seed()}catch{items=seed()}
 let view='fila',selected=null,query='',onlyLate=false;const app=document.querySelector('#app'),dialog=document.querySelector('#detail'),edit=document.querySelector('#edit');
 const partner=id=>partners.find(p=>p.id===id), late=x=>!['Fechado','Perdido'].includes(x.status)&&x.due<date(), stamp=()=>new Date().toLocaleString('pt-BR');
 function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',4000)}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(items));return true}catch{toast('Não foi possível salvar neste navegador.');return false}}
 function link(p){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('corretor',p.id);return u.href}
 function stats(){return `<div class="stats"><div class="stat"><small>INDICAÇÕES</small><strong>${items.length}</strong></div><div class="stat alert"><small>AÇÕES ATRASADAS</small><strong>${items.filter(late).length}</strong></div><div class="stat"><small>EM ATENDIMENTO</small><strong>${items.filter(x=>!['Fechado','Perdido'].includes(x.status)).length}</strong></div><div class="stat"><small>NEGÓCIOS FECHADOS</small><strong>${items.filter(x=>x.status==='Fechado').length}</strong></div></div>`}
 function row(x){return `<article class="card row ${late(x)?'overdue':''}"><div><h3>${esc(x.name)}</h3><p>${esc(partner(x.partner).name)} · ${esc(partner(x.partner).agency)}</p><span class="pill">${esc(x.status)}</span></div><div><small>RESPONSÁVEL</small><p>${esc(x.owner)}</p></div><div><p>${esc(x.action)}</p><span class="pill ${late(x)?'late':''}">${late(x)?'Atrasada · ':''}${fmt(x.due)}</span></div><button data-open="${esc(x.id)}">Abrir ficha →</button></article>`}
 function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));app.innerHTML=stats();
 if(view==='fila'){app.innerHTML+=`<div class="toolbar"><h2>Fila de atendimento</h2><input id="search" aria-label="Buscar cliente" placeholder="Buscar cliente" value="${esc(query)}"><button id="late-filter" aria-pressed="${onlyLate}">${onlyLate?'Mostrar todas':'Só atrasadas'}</button></div><div class="rows" id="rows"></div>`;renderRows();document.querySelector('#search').oninput=e=>{query=e.target.value;renderRows()};document.querySelector('#late-filter').onclick=()=>{onlyLate=!onlyLate;render()}}
 if(view==='funil'){app.innerHTML+=`<h2>Funil de indicações</h2><p>Abra uma ficha para atualizar o status e definir o próximo passo.</p><div class="board">${statuses.map(s=>{const list=items.filter(x=>x.status===s);return `<section class="column"><h3>${s} · ${list.length}</h3>${list.map(x=>`<article class="card"><h3>${esc(x.name)}</h3><p>${esc(partner(x.partner).name)}</p><p>${money(x.value)}</p>${late(x)?'<span class="pill late">Ação atrasada</span>':''}<button data-open="${esc(x.id)}">Abrir ficha</button></article>`).join('')||'<p>Nenhuma indicação</p>'}</section>`}).join('')}</div>`}
 if(view==='parceiros'){app.innerHTML+=`<h2>Parceiros e links fixos</h2><p>Cada corretor tem seu próprio formulário. Nesta demonstração, os envios aparecem somente no navegador em que forem realizados.</p><div class="grid">${partners.map(p=>`<article class="card"><span class="pill">Corretor · demonstração</span><h2>${p.name}</h2><p>${p.agency}</p><strong>${items.filter(x=>x.partner===p.id).length} indicações</strong><div class="link">${esc(link(p))}</div><div class="toolbar"><button data-copy="${p.id}">Copiar link</button><a href="${esc(link(p))}" target="_blank" rel="noopener">Testar formulário ↗</a></div></article>`).join('')}</div>`}
 if(view==='comissoes'){app.innerHTML+=`<h2>Comissões demonstrativas</h2><p>Simulação de 10% sobre o valor fechado. Liberar ou marcar como paga apenas altera esta demonstração; não realiza pagamentos.</p><div class="rows">${items.filter(x=>x.status==='Fechado').map(x=>`<article class="card row"><div><h3>${esc(x.name)}</h3><p>${esc(partner(x.partner).name)}</p></div><strong>${money(x.value*.1)}</strong><span class="pill">${esc(x.payment)}</span>${x.payment==='Paga'?'<span>Pagamento simulado</span>':`<button data-pay="${esc(x.id)}">${x.payment==='Prevista'?'Simular liberação':'Simular pagamento'}</button>`}</article>`).join('')||'<p>Nenhuma indicação fechada.</p>'}</div>`}
 }
 function renderRows(){const list=items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&(!onlyLate||late(x))).sort((a,b)=>Number(late(b))-Number(late(a))||a.due.localeCompare(b.due));document.querySelector('#rows').innerHTML=list.map(row).join('')||'<div class="panel empty">Nenhuma indicação encontrada.</div>'}
 function open(id){selected=items.find(x=>x.id===id);if(!selected)return;document.querySelector('#detail-title').textContent=selected.name;document.querySelector('#origin').textContent=`${partner(selected.partner).name} · ${partner(selected.partner).agency} · Telefone fictício: ${selected.phone}`;edit.elements.status.innerHTML=statuses.map(s=>`<option>${s}</option>`).join('');for(const k of ['status','owner','action','due'])edit.elements[k].value=selected[k];document.querySelector('#history').innerHTML=selected.history.map(h=>`<li>${esc(h)}</li>`).join('');dialog.showModal()}
 edit.onsubmit=e=>{e.preventDefault();const old=selected.status;for(const k of ['status','owner','action','due'])selected[k]=edit.elements[k].value.trim();selected.history.unshift(`${stamp()} · Gestor Demo: ${old} → ${selected.status}. Responsável: ${selected.owner}. Próxima ação: ${selected.action}, ${fmt(selected.due)}.`);save();dialog.close();render();toast('Acompanhamento salvo na demonstração.')};document.querySelector('#close').onclick=()=>dialog.close();
 app.onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open)open(b.dataset.open);if(b.dataset.copy){try{await navigator.clipboard.writeText(link(partner(b.dataset.copy)));toast('Link demonstrativo copiado.')}catch{toast('Copie o endereço exibido no cartão.')}}if(b.dataset.pay){const x=items.find(x=>x.id===b.dataset.pay);x.payment=x.payment==='Prevista'?'Liberada':'Paga';x.history.unshift(`${stamp()} · Gestor Demo: comissão ${x.payment.toLowerCase()} (simulação).`);save();render()}};
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(location.search){location.href=location.pathname+'#'+b.dataset.view;return}view=b.dataset.view;render()});
 document.querySelector('#reset').onclick=()=>{if(confirm('Reiniciar apenas os dados desta demonstração?')){items=seed();save();location.href=location.pathname}};
 window.addEventListener('storage',e=>{if(e.key===KEY&&!location.search){try{const next=JSON.parse(e.newValue);if(Array.isArray(next)){items=next;if(!dialog.open)render()}}catch{}}});
 const token=new URLSearchParams(location.search).get('corretor');
 if(token){document.querySelector('aside').hidden=true;document.querySelector('main').style.marginLeft='0';document.querySelector('#reset').hidden=true;document.querySelector('h1').textContent='Uma indicação, um novo começo';document.querySelector('#subtitle').textContent='Formulário de demonstração';const p=partner(token);if(!p){app.innerHTML='<div class="panel">Link demonstrativo inválido.</div>';return}app.innerHTML=`<section class="panel public"><span class="pill">Indicado por ${p.name}</span><h2>Conte para nós quem você quer indicar</h2><p>${p.agency} · A origem fica vinculada automaticamente a este link.</p><form id="referral"><label>Nome fictício do cliente<input name="name" required minlength="2" maxlength="100" placeholder="Ex.: Cliente Teste"></label><label>Telefone fictício<input name="phone" required inputmode="tel" placeholder="Ex.: (11) 90000-0099" maxlength="20"></label><label>O que o cliente procura?<textarea name="notes" maxlength="500" placeholder="Ex.: projeto para apartamento"></textarea></label><p id="form-error" class="error" role="alert"></p><button class="primary">Enviar indicação de teste</button></form><div id="success" hidden><h3>Indicação recebida nesta demonstração!</h3><p>A origem foi preservada. Você pode usar o mesmo link para indicar outro cliente.</p><button id="another">Indicar outro cliente</button><p><a href="indicacoes-demo.html">Ver fila demonstrativa →</a></p></div></section>`;
 const f=document.querySelector('#referral');f.onsubmit=e=>{e.preventDefault();const phone=f.elements.phone.value.replace(/\D/g,'').replace(/^55(?=\d{10,11}$)/,'');const err=document.querySelector('#form-error');if(!/^\d{10,11}$/.test(phone)){err.textContent='Informe um telefone de teste com DDD, com 10 ou 11 dígitos.';return}try{const stored=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(stored))items=stored}catch{}if(items.some(x=>x.phone===phone)){err.textContent='Este telefone já possui uma indicação nesta demonstração.';return}items.unshift({id:uid(),name:f.elements.name.value.trim(),phone,partner:p.id,status:statuses[0],owner:'Marina · Comercial',action:'Fazer primeiro contato',due:date(1),value:0,payment:'Prevista',history:[`${stamp()} · Enviado pelo link demonstrativo de ${p.name}.`,f.elements.notes.value.trim()||'Sem observações.']});if(!save())return;f.hidden=true;document.querySelector('#success').hidden=false};document.querySelector('#another').onclick=()=>{f.reset();document.querySelector('#form-error').textContent='';f.hidden=false;document.querySelector('#success').hidden=true;f.elements.name.focus()};save();
 }else{if(['fila','funil','parceiros','comissoes'].includes(location.hash.slice(1)))view=location.hash.slice(1);save();render()}
})();

