(()=>{'use strict';
 const endpoint='https://vlvadvlfsbgwcldaxhah.supabase.co/functions/v1/camber-referrals',key='sb_publishable_le8I7BGWpHrvdWqxjQKwdg_YUEyZJL-';
 const statuses=['Novo Lead','Contato Feito','Reunião Agendada','Proposta Enviada','Fechado','Perdido'];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),fmt=d=>d?String(d).slice(0,10).split('-').reverse().join('/'):'Sem prazo';
 let data={state:{indicacoes:[],corretores:[]},users:[],links:[]},view='fila',query='',filter='active',selected=null,busy=false;
 const app=document.querySelector('#app'),dialog=document.querySelector('#detail'),edit=document.querySelector('#edit');
 const items=()=>data.state.indicacoes||[],partners=()=>data.state.corretores||[],late=x=>!x.archived&&!['Fechado','Perdido'].includes(x.status)&&x.nextActionDate&&x.nextActionDate<today();
 const partner=x=>x.partnerName||partners().find(p=>p.id===x.corretorId)?.nome||'Parceiro não localizado';
 async function call(action,payload={}){const client=window.CamberCloud?.client();if(!client)throw Error('Aguarde a conexão com o sistema.');const {data:session,error}=await client.auth.getSession();if(error||!session.session)throw Error('Entre no sistema para acessar as indicações.');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+session.session.access_token},body:JSON.stringify({action,payload}),signal:AbortSignal.timeout(20000)});const result=await r.json();if(!r.ok||result.error)throw Error(result.error||'Não foi possível concluir.');return result}
 function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',4000)}
 async function load(){document.querySelector('#error').textContent='';try{data=await call('read');render()}catch(e){document.querySelector('#error').textContent=e.message;if(!items().length)app.textContent='Não foi possível carregar. Use Atualizar após entrar no sistema.'}}
 function stats(){const active=items().filter(x=>!x.archived);return `<div class="stats"><div class="stat"><small>INDICAÇÕES ATIVAS</small><strong>${active.length}</strong></div><div class="stat alert"><small>AÇÕES ATRASADAS</small><strong>${active.filter(late).length}</strong></div><div class="stat"><small>SEM RESPONSÁVEL</small><strong>${active.filter(x=>!x.ownerId&&!['Fechado','Perdido'].includes(x.status)).length}</strong></div><div class="stat"><small>NEGÓCIOS FECHADOS</small><strong>${active.filter(x=>x.status==='Fechado').length}</strong></div></div>`}
 function row(x){return `<article class="card row ${late(x)?'overdue':''}"><div><h3>${esc(x.clienteNome)}</h3><p>${esc(partner(x))}</p><span class="pill">${esc(x.status)}${x.archived?' · Arquivada':''}</span></div><div><small>RESPONSÁVEL</small><p>${esc(x.ownerName||'Não atribuído')}</p></div><div><p>${esc(x.nextAction||'Definir próximo passo')}</p><span class="pill ${late(x)?'late':''}">${late(x)?'Atrasada · ':''}${fmt(x.nextActionDate)}</span></div><div><button data-open="${esc(x.id)}">Abrir ficha →</button>${x.status==='Fechado'?`<a class="manage" target="_top" href="precificacao.html?novo=1&amp;fromInd=${encodeURIComponent(x.id)}&amp;cliente=${encodeURIComponent(x.clienteNome)}&amp;valor=${encodeURIComponent(x.valorReal||0)}">Abrir precificação →</a>`:''}</div></article>`}
 function renderRows(){const list=items().filter(x=>(filter==='archived'?x.archived:!x.archived)&&(filter!=='late'||late(x))&&[x.clienteNome,x.clienteTel,partner(x),x.ownerName].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(late(b))-Number(late(a))||String(a.nextActionDate||'9999').localeCompare(b.nextActionDate||'9999'));document.querySelector('#rows').innerHTML=list.map(row).join('')||'<div class="panel empty">Nenhuma indicação nesta seleção.</div>'}
 function rate(x){if(x.commRate!=null)return Number(x.commRate);return Number((data.state.config?.faixas||[]).find(f=>f.ate==null||Number(x.valorReal||0)<=f.ate)?.pct||0)/100}
 function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));app.innerHTML=stats();
 if(view==='fila'){app.innerHTML+=`<div class="toolbar"><h2>Fila de atendimento</h2><input id="search" aria-label="Buscar indicações" placeholder="Cliente, telefone ou responsável" value="${esc(query)}"><select id="filter" aria-label="Filtrar indicações"><option value="active">Ativas</option><option value="late">Só atrasadas</option><option value="archived">Arquivadas</option></select></div><div class="rows" id="rows"></div>`;document.querySelector('#filter').value=filter;document.querySelector('#filter').onchange=e=>{filter=e.target.value;renderRows()};document.querySelector('#search').oninput=e=>{query=e.target.value;renderRows()};renderRows()}
 if(view==='funil')app.innerHTML+=`<h2>Funil de indicações</h2><p class="helper">Arraste uma indicação para outra etapa. No celular ou pelo teclado, use “Mover para”. Ao fechar, confirme o valor do contrato na ficha.</p><div class="board">${statuses.map(s=>{const list=items().filter(x=>!x.archived&&x.status===s);return `<section class="column" data-drop-status="${esc(s)}" aria-label="${esc(s)}"><h3>${s} · ${list.length}</h3>${list.map(x=>`<article class="card referral-card" draggable="true" data-drag-id="${esc(x.id)}"><span class="drag-hint" aria-hidden="true">⠿ Arraste para mover</span><h3>${esc(x.clienteNome)}</h3><p>${esc(partner(x))}</p><p>${money(x.valorReal||x.valorEstimado)}</p><p>${esc(x.ownerName||'Não atribuído')}</p>${late(x)?'<span class="pill late">Ação atrasada</span>':''}<label class="move-label">Mover para<select data-move-id="${esc(x.id)}" aria-label="Mover ${esc(x.clienteNome)} para outra etapa">${statuses.map(t=>`<option${t===s?' selected':''}>${t}</option>`).join('')}</select></label><button data-open="${esc(x.id)}">Abrir ficha</button></article>`).join('')||'<p>Solte uma indicação aqui</p>'}</section>`}).join('')}</div>`;
 if(view==='parceiros')app.innerHTML+=`<h2>Corretores e links fixos</h2><p>O link identifica automaticamente o corretor e permite enviar novos clientes sem entrar no sistema. Compartilhe somente com o corretor correspondente.</p><div class="grid">${partners().map(p=>{const l=data.links.find(l=>String(l.partner_id)===String(p.id)),url=l?new URL('indicar.html?token='+l.token,location.href).href:'',list=items().filter(x=>x.corretorId===p.id);return `<article class="card"><h3>${esc(p.nome)}</h3><p>${esc(p.imob||'Corretor independente')}</p><p>${list.length} indicações · ${list.filter(x=>x.status==='Fechado').length} fechadas</p>${l?`<span class="pill ${l.active?'':'late'}">Link ${l.active?'ativo':'desativado'}</span><div class="link">${esc(url)}</div><div class="link-actions"><button data-copy="${esc(url)}">Copiar link</button><button data-link="${p.id}" data-mode="toggle">${l.active?'Desativar':'Ativar'}</button><button data-link="${p.id}" data-mode="rotate">Substituir link</button></div>${l.active?`<a class="manage" href="${esc(url)}" target="_blank" rel="noopener">Abrir formulário ↗</a>`:''}`:`<button data-link="${p.id}" data-mode="create">Criar link fixo</button>`}</article>`}).join('')||'<div class="panel">Cadastre um corretor em “Cadastros, nova indicação e regras”.</div>'}</div>`;
 if(view==='comissoes'){const closed=items().filter(x=>x.status==='Fechado');app.innerHTML+=`<h2>Comissões</h2><p>Valores usam as regras cadastradas. Registrar pagamento apenas documenta um pagamento já realizado; não transfere dinheiro.</p><div class="rows">${closed.map(x=>`<article class="card row"><div><h3>${esc(x.clienteNome)}</h3><p>${esc(partner(x))}</p><button data-open="${esc(x.id)}">Abrir ficha</button></div><div><strong>${money(Number(x.valorReal||0)*rate(x))}</strong><p>${(rate(x)*100).toLocaleString('pt-BR')}% de ${money(x.valorReal)}</p></div><div><span class="pill">${esc(x.paymentStatus||'Prevista')}</span>${x.paidAt?`<p>${fmt(x.paidAt)} · ${esc(x.paymentReference)}</p>`:''}</div>${data.admin&&x.paymentStatus!=='Paga'?`<button data-pay="${esc(x.id)}">${x.paymentStatus==='Liberada'?'Registrar pagamento':'Liberar comissão'}</button>`:'<span>Registro financeiro</span>'}</article>`).join('')||'<div class="panel empty">Nenhum contrato fechado.</div>'}</div>`}
 }
 function open(id){selected=items().find(x=>String(x.id)===String(id));if(!selected)return;document.querySelector('#detail-title').textContent=selected.clienteNome;document.querySelector('#origin').textContent='Origem: '+partner(selected)+(selected.source==='broker-link'?' · Link do corretor':'');document.querySelector('#contact').textContent=[selected.clienteTel,selected.clienteEmail].filter(Boolean).join(' · ');document.querySelector('#notes').textContent=[selected.contexto,selected.obs].filter(Boolean).join(' — ');edit.elements.status.innerHTML=statuses.map(s=>`<option>${s}</option>`).join('');edit.elements.owner.innerHTML='<option value="">Não atribuído</option>'+data.users.map(u=>`<option value="${esc(u.id)}">${esc(u.nome)}</option>`).join('');edit.elements.status.value=selected.status;edit.elements.owner.value=selected.ownerId||'';edit.elements.action.value=selected.nextAction||'';edit.elements.due.value=selected.nextActionDate||'';edit.elements.value.value=selected.valorReal||selected.valorEstimado||0;document.querySelector('#edit-error').textContent='';document.querySelector('#archive').textContent=selected.archived?'Restaurar':'Arquivar';document.querySelector('#history').innerHTML=(selected.logs||[]).slice().reverse().map(l=>`<li><strong>${esc(l.userName||'Histórico antigo')}</strong> · ${esc(new Date(l.data).toLocaleString('pt-BR'))}<br>${esc(l.previousStatus?l.previousStatus+' → ':'')}${esc(l.status)}<br>${esc(l.nota)}</li>`).join('');dialog.showModal()}
 async function mutate(action,payload){if(busy)return false;busy=true;window.CamberReferralsBusy=true;document.querySelectorAll('button,[data-move-id]').forEach(b=>b.disabled=true);app.setAttribute('aria-busy','true');try{await call(action,payload);return true}finally{busy=false;window.CamberReferralsBusy=false;document.querySelectorAll('button,[data-move-id]').forEach(b=>b.disabled=false);app.setAttribute('aria-busy','false')}}
 let draggedId=null;
 function clearDrag(){draggedId=null;app.querySelectorAll('.dragging,.drop-target').forEach(el=>el.classList.remove('dragging','drop-target'))}
 async function moveReferral(id,status){
  if(busy||!statuses.includes(status))return;
  const x=items().find(x=>String(x.id)===String(id));if(!x||x.archived||x.status===status)return;
  if(x.paymentStatus==='Paga'){toast('Esta indicação tem comissão paga. O status deve permanecer Fechado.');render();return}
  if(status==='Fechado'||(!['Fechado','Perdido'].includes(status)&&(!x.nextAction?.trim()||!x.nextActionDate))){
   open(id);edit.elements.status.value=status;document.querySelector('#edit-error').textContent=status==='Fechado'?'Confira o valor do contrato e salve para concluir a movimentação.':'Informe a próxima ação e sua data para concluir a movimentação.';render();return;
  }
  document.querySelector('#error').textContent='';
  try{if(await mutate('update',{id:String(x.id),revision:x.revision||0,status,ownerId:x.ownerId||'',nextAction:x.nextAction||'',nextActionDate:x.nextActionDate||'',value:Number(x.valorReal??x.valorEstimado??0)})){await load();toast('Indicação movida para '+status+'.')}}catch(e){document.querySelector('#error').textContent=e.message;render()}
 }
 app.addEventListener('dragstart',e=>{const card=e.target.closest('[data-drag-id]');if(!card||busy||e.target.closest('button,select,a,input')){e.preventDefault();return}draggedId=card.dataset.dragId;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',draggedId);card.classList.add('dragging')});
 app.addEventListener('dragover',e=>{const column=e.target.closest('[data-drop-status]');if(!column||!draggedId||busy)return;e.preventDefault();e.dataTransfer.dropEffect='move';app.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));column.classList.add('drop-target')});
 app.addEventListener('dragleave',e=>{const column=e.target.closest('[data-drop-status]');if(column&&!column.contains(e.relatedTarget))column.classList.remove('drop-target')});
 app.addEventListener('drop',e=>{const column=e.target.closest('[data-drop-status]'),id=draggedId;e.preventDefault();clearDrag();if(column&&id&&!busy)moveReferral(id,column.dataset.dropStatus)});
 app.addEventListener('dragend',clearDrag);
 app.addEventListener('change',e=>{const select=e.target.closest('[data-move-id]');if(!select)return;const status=select.value,x=items().find(x=>String(x.id)===select.dataset.moveId);if(x)select.value=x.status;moveReferral(select.dataset.moveId,status)});
 edit.onsubmit=async e=>{e.preventDefault();try{const ok=await mutate('update',{id:String(selected.id),revision:selected.revision||0,status:edit.elements.status.value,ownerId:edit.elements.owner.value,nextAction:edit.elements.action.value.trim(),nextActionDate:edit.elements.due.value,value:Number(edit.elements.value.value)});if(ok){dialog.close();await load();toast('Acompanhamento salvo.')}}catch(e){document.querySelector('#edit-error').textContent=e.message}};
 document.querySelector('#close').onclick=()=>dialog.close();document.querySelector('#archive').onclick=async()=>{try{if(await mutate('archive',{id:String(selected.id),revision:selected.revision||0})){dialog.close();await load()}}catch(e){document.querySelector('#edit-error').textContent=e.message}};
 app.onclick=async e=>{const b=e.target.closest('button');if(!b||busy)return;try{if(b.dataset.open)open(b.dataset.open);if(b.dataset.copy){try{await navigator.clipboard.writeText(b.dataset.copy);toast('Link copiado.')}catch{toast('Selecione e copie o endereço exibido no cartão.')}}if(b.dataset.link){if(b.dataset.mode==='rotate'&&!confirm('Substituir o link? O endereço anterior deixará de receber indicações.'))return;if(await mutate('link',{partnerId:b.dataset.link,mode:b.dataset.mode}))await load()}if(b.dataset.pay){const x=items().find(x=>String(x.id)===b.dataset.pay);let reference='';if(x.paymentStatus==='Liberada'){reference=prompt('Referência do pagamento já realizado (comprovante, transferência ou observação):');if(reference===null)return}if(await mutate('payment',{id:String(x.id),revision:x.revision||0,reference}))await load()}}catch(e){document.querySelector('#error').textContent=e.message}};
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelector('#refresh').onclick=load;
 let attempts=0;const timer=setInterval(()=>{if(window.CamberCloud?.client()){clearInterval(timer);load()}else if(++attempts>20){clearInterval(timer);app.innerHTML='<p>Entre no sistema para carregar as indicações reais. Para testar com dados fictícios, <a href="indicacoes-demo.html">abra a demonstração</a>.</p>'}},500);
})();
