(()=>{'use strict';
 const endpoint='https://vlvadvlfsbgwcldaxhah.supabase.co/functions/v1/camber-referrals',key='sb_publishable_le8I7BGWpHrvdWqxjQKwdg_YUEyZJL-';
 const token=new URLSearchParams(location.search).get('token'),f=document.querySelector('#public-form'),err=document.querySelector('#public-error');let busy=false,requestId=makeId();
 function makeId(){const a=new Uint8Array(20);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')}
 async function call(action,payload){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:key},body:JSON.stringify({action,payload}),signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok||data.error)throw Error(data.error||'Não foi possível enviar. Tente novamente.');return data}
 async function init(){try{if(!token)throw Error('Link inválido. Solicite o link ao seu corretor.');const p=await call('lookup',{token});document.querySelector('#public-origin').textContent='Indicação por '+p.name+(p.agency?' · '+p.agency:'');f.hidden=false}catch(e){err.textContent=e.message;document.querySelector('#public-origin').textContent='Link indisponível'}}
 f.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=document.querySelector('#send');b.disabled=true;b.textContent='Enviando…';err.textContent='';try{const values=Object.fromEntries(new FormData(f));await call('submit',{...values,token,requestId,consent:f.elements.consent.checked});f.hidden=true;document.querySelector('#success').hidden=false}catch(e){err.textContent=e.name==='TimeoutError'?'O servidor demorou a responder. Tente enviar novamente; o mesmo envio não será duplicado.':e.message}finally{busy=false;b.disabled=false;b.textContent='Enviar indicação'}};
 document.querySelector('#another').onclick=()=>{requestId=makeId();f.reset();err.textContent='';document.querySelector('#success').hidden=true;f.hidden=false;f.elements.name.focus()};init();
})();
