(function(){
'use strict';
if(!window.PROJ || !projId)return;
var area=new URLSearchParams(location.search).get('area')||'',wrap=document.querySelector('#app .wrap');
function e(t,s){var n=document.createElement(t);if(s)n.textContent=s;return n;}
function url(a){return 'projeto.html?id='+encodeURIComponent(projId)+(a?'&area='+a:'');}
var css=e('style');css.textContent=`
#app .wrap > [hidden]{display:none!important}#app .area-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}#app .area-card{display:block;text-decoration:none;color:var(--ink);background:var(--surface);border:1px solid var(--hair-2);border-radius:18px;padding:28px;transition:.2s}#app .area-card:hover{transform:translateY(-3px);border-color:var(--accent);box-shadow:0 12px 30px #40302010}#app .area-card h2{font-size:22px;margin:24px 0 8px}#app .area-card p{color:var(--ink-3);font-size:13px;line-height:1.6}#app .area-icon{display:inline-grid;place-items:center;width:46px;height:46px;border-radius:13px;background:#f3e5d8;color:#aa633b;font-size:22px}#app .area-card:nth-child(2) .area-icon{background:#e8eddf;color:#6f805a}#app .area-card:nth-child(3) .area-icon{background:#f3ecd8;color:#9b8341}#app .area-card:nth-child(4) .area-icon{background:#e4ecee;color:#698791}#app .area-link{display:block;border-top:1px solid var(--hair);margin-top:24px;padding-top:15px;font-size:12px;color:var(--accent)}#app .area-back{color:var(--ink-3);text-decoration:none;font-size:13px;margin:8px 0 15px;display:block}#app .area-heading{font-size:30px;margin:0}#app.area-services #ct-ov{display:block!important;position:static!important;background:none!important;padding:0!important;z-index:auto!important}#app.area-services #ct-ov .modal{width:100%;max-width:none;max-height:none;box-shadow:none;transform:none;margin:0}#app.area-services .modal-close{display:none}body.area-visits #visDrawer{display:block!important;position:static!important;width:100%!important;max-width:none!important;max-height:none!important;transform:none!important;margin:0;box-shadow:none;opacity:1!important;visibility:visible!important}body.area-visits #visDrawer .vis-drawer-b{max-height:none}body.area-visits .vis-drawer-x,body.area-visits .vis-grip,body.area-visits #visDrawerScrim{display:none!important}#app .schedule-form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr 1fr;gap:12px;align-items:end}#app .schedule-form label{font-size:12px;color:var(--ink-3)}#app .schedule-form input,#app .schedule-form select{display:block;width:100%;padding:10px;border:1px solid var(--hair-2);border-radius:8px;font:inherit;background:var(--surface);color:var(--ink);margin-top:6px}#app .schedule-row{display:flex;gap:20px;align-items:center;justify-content:space-between;padding:18px 0;border-bottom:1px solid var(--hair);flex-wrap:wrap}@media(max-width:750px){#app .area-grid{grid-template-columns:1fr}#app .schedule-form{grid-template-columns:1fr 1fr}}`;
document.head.append(css);
var back=e('a',area?'← Áreas do projeto':'← Todos os projetos');back.href=area?url(''):'projetos.html';back.className='area-back';
if(area==='oportunidades'){wrap.prepend(back);return;}
Array.from(wrap.children).forEach(function(n){n.hidden=true;});wrap.append(back);
var h=e('h1',area==='servicos'?'Serviços terceirizados':area==='visitas'?'Controle de visitas':area==='cronograma'?'Cronograma da obra':PROJ.nome);h.className='area-heading';wrap.append(h,e('p',area?PROJ.nome:[PROJ.cliente,PROJ.cidade,PROJ.uf].filter(Boolean).join(' · ')));
if(!area){var grid=e('div');grid.className='area-grid';[['oportunidades','▥','Oportunidades comerciais','Acompanhe propostas, negociações e fechamentos.'],['cronograma','▦','Cronograma da obra','Organize etapas, prazos e responsáveis pela execução.'],['servicos','◇','Serviços terceirizados','Reúna prestadores, serviços contratados e custos.'],['visitas','◎','Controle de visitas','Registre horários, localização e acompanhamento da obra.']].forEach(function(m){var a=e('a');a.href=url(m[0]);a.className='area-card';var icon=e('span',m[1]);icon.className='area-icon';var link=e('span','Acessar →');link.className='area-link';a.append(icon,e('h2',m[2]),e('p',m[3]),link);grid.append(a);});wrap.append(grid);return;}
if(area==='servicos'){document.getElementById('app').classList.add('area-services');var panel=document.getElementById('ct-ov');wrap.append(panel);CT.open(projId,function(){});return;}
if(area==='visitas'){document.body.classList.add('area-visits');wrap.append(document.getElementById('visDrawer'));Visitas.open();return;}
if(area!=='cronograma'){location.replace(url(''));return;}
var box=e('div');box.className='panel';box.style.padding='24px';var form=e('form');form.className='schedule-form';
function field(label,name,type){var l=e('label',label),i=e('input');i.name=name;i.type=type||'text';l.append(i);form.append(l);return i;}
var name=field('Etapa','title');name.required=true;var responsible=field('Responsável','responsible'),start=field('Início','start','date'),end=field('Fim previsto','end','date');var label=e('label','Status'),select=e('select');['A iniciar','Em andamento','Concluído'].forEach(function(v){select.add(new Option(v,v));});label.append(select);form.append(label);var save=e('button','Adicionar etapa');save.className='btn primary';save.type='submit';var cancel=e('button','Cancelar edição');cancel.type='button';cancel.className='btn';cancel.hidden=true;form.append(save,cancel);var status=e('p');status.setAttribute('role','status');var list=e('div');box.append(form,status,list);wrap.append(box);var editing=null,busy=false;
function rows(){return (CamberDB.getProject(projId)||{}).cronograma||[];}
function reset(){editing=null;form.reset();save.textContent='Adicionar etapa';cancel.hidden=true;}
cancel.onclick=reset;
async function persist(data){CamberDB.updateProject(projId,{cronograma:data});if(window.CamberCloud)await CamberCloud.flush();}
function draw(){list.replaceChildren();var data=rows();if(!data.length)list.append(e('p','Nenhuma etapa cadastrada. Adicione a primeira etapa da obra.'));data.forEach(function(r){var row=e('div');row.className='schedule-row';var desc=e('div');desc.append(e('strong',r.title),e('p',[r.responsible,r.start,r.end,r.status].filter(Boolean).join(' · ')));var actions=e('div'),edit=e('button','Editar'),del=e('button','Excluir');edit.className=del.className='btn';edit.onclick=function(){if(busy)return;editing=r.id;name.value=r.title;responsible.value=r.responsible||'';start.value=r.start||'';end.value=r.end||'';select.value=r.status;save.textContent='Salvar etapa';cancel.hidden=false;name.focus();};del.onclick=async function(){if(busy||!confirm('Excluir a etapa "'+r.title+'"?'))return;busy=true;try{await persist(rows().filter(function(x){return x.id!==r.id;}));reset();draw();status.textContent='Etapa excluída.';}catch(err){draw();status.textContent='Não foi possível sincronizar. Confira sua conexão antes de sair.';}finally{busy=false;}};actions.append(edit,del);row.append(desc,actions);list.append(row);});}
form.onsubmit=async function(ev){ev.preventDefault();if(busy)return;if(start.value&&end.value&&end.value<start.value){status.textContent='O fim previsto deve ser igual ou posterior ao início.';return;}busy=true;save.disabled=true;var id=editing||crypto.randomUUID(),data=rows().slice(),record={id:id,title:name.value.trim(),responsible:responsible.value.trim(),start:start.value,end:end.value,status:select.value};if(!record.title){busy=false;save.disabled=false;return;}var idx=data.findIndex(function(r){return r.id===id;});if(idx<0)data.push(record);else data[idx]=record;editing=id;try{await persist(data);reset();draw();status.textContent='Cronograma salvo.';}catch(err){draw();status.textContent='Não foi possível confirmar o salvamento. Confira sua conexão e tente salvar novamente.';}finally{busy=false;save.disabled=false;}};draw();
})();
