(function(){
'use strict';
var el=function(id){return document.getElementById(id);},busy=false,allowed=false;
var hash=new URLSearchParams(location.hash.slice(1)),recovery=hash.get('type')==='recovery',invalid=hash.has('error')||hash.has('error_code');
if(!window.supabase){el('msg').textContent='Não foi possível conectar. Atualize a página e tente novamente.';el('send').disabled=true;return;}
var sb=supabase.createClient('https://vlvadvlfsbgwcldaxhah.supabase.co','sb_publishable_le8I7BGWpHrvdWqxjQKwdg_YUEyZJL-',{auth:{storageKey:'mabe-auth',flowType:'implicit',detectSessionInUrl:true}});
function showReset(){allowed=true;el('request').hidden=true;el('reset').hidden=false;el('title').textContent='Criar nova senha';el('intro').textContent='Escolha uma nova senha para acessar o CRM.';el('msg').textContent='';history.replaceState(null,'',location.pathname);}
if(invalid){el('msg').textContent='Este link expirou ou já foi utilizado. Solicite um novo abaixo.';history.replaceState(null,'',location.pathname);}
if(recovery&&!invalid){el('send').disabled=true;el('msg').textContent='Validando seu link…';sb.auth.getSession().then(function(r){if(r.error||!r.data.session)throw new Error('invalid');return sb.auth.getUser();}).then(function(r){if(r.error||!r.data.user)throw new Error('invalid');showReset();}).catch(function(){el('send').disabled=false;el('msg').textContent='Link inválido ou expirado. Solicite um novo.';history.replaceState(null,'',location.pathname);});}
el('request').onsubmit=async function(e){e.preventDefault();if(busy)return;busy=true;el('send').disabled=true;el('msg').textContent='Enviando…';try{var r=await sb.auth.resetPasswordForEmail(el('email').value.trim(),{redirectTo:'https://app.camberinteriores.com.br/recuperar-senha.html'});if(r.error)throw r.error;el('msg').textContent='Se o e-mail estiver cadastrado, você receberá um link. Confira também o spam.';setTimeout(function(){el('send').disabled=false;busy=false;},60000);}catch(err){el('msg').textContent=err.status===429?'Aguarde alguns minutos antes de pedir outro link.':'Não foi possível enviar o link. Tente novamente mais tarde.';busy=false;el('send').disabled=false;}};
el('reset').onsubmit=async function(e){e.preventDefault();if(busy||!allowed)return;var password=el('password').value;if(password.length<8||password!==el('confirm').value){el('msg').textContent='As senhas devem ser iguais e ter pelo menos 8 caracteres.';return;}busy=true;el('save').disabled=true;el('msg').textContent='Salvando…';try{var r=await sb.auth.updateUser({password:password});if(r.error)throw r.error;allowed=false;el('password').value=el('confirm').value='';el('reset').hidden=true;el('title').textContent='Senha atualizada';el('intro').textContent='Sua nova senha foi salva. Volte para o login para entrar no CRM.';el('msg').textContent='';await sb.auth.signOut({scope:'local'});sessionStorage.removeItem('mabe_cloud_hydrated');}catch(err){el('msg').textContent='Não foi possível alterar a senha. Use uma senha diferente ou solicite um novo link se ele expirou.';}finally{busy=false;el('save').disabled=false;}};
})();
