create table public.cliente_convites (
  id bigint generated by default as identity primary key,
  token text not null unique default replace(gen_random_uuid()::text,'-',''),
  status text not null default 'pendente' check(status in ('pendente','respondido','cadastrado')),
  nome_hint text, created_by text, created_at timestamptz not null default now(),
  respondido_em timestamptz, notificado_7d boolean not null default false, dados jsonb
);
alter table public.cliente_convites enable row level security;
revoke all on public.cliente_convites from anon, public;
grant select,insert,update,delete on public.cliente_convites to authenticated;
grant usage,select on sequence public.cliente_convites_id_seq to authenticated;
create policy cliente_conv_sel on public.cliente_convites for select to authenticated using(public.is_aprovado());
create policy cliente_conv_ins on public.cliente_convites for insert to authenticated with check(public.is_aprovado() and status='pendente' and dados is null);
create policy cliente_conv_upd on public.cliente_convites for update to authenticated using(public.is_aprovado()) with check(public.is_aprovado());
create policy cliente_conv_del on public.cliente_convites for delete to authenticated using(public.is_aprovado() and status in ('pendente','respondido'));
create index cliente_convites_status_created on public.cliente_convites(status,created_at);

-- Preserve the existing webhook configuration server-side; do not export secrets.
do $clone$
declare body text; a integer; b integer;
begin
 body:=replace(pg_get_functiondef('public.get_convite_fornecedor(text)'::regprocedure),'fornecedor','cliente');
 execute body;
 body:=replace(pg_get_functiondef('public.responder_convite_fornecedor(text,jsonb)'::regprocedure),'fornecedor','cliente');
 body:=replace(body,'''nome'',''fantasia'',''doc'',''contato'',''tel'',''email'',''cep'',''logradouro'',''numero'',''bairro'',''cidade'',''uf'',''banco'',''agencia'',''conta'',''nomeConta'',''pix''','''nome'',''doc'',''contato'',''tel'',''email'',''cep'',''logradouro'',''numero'',''bairro'',''cidade'',''uf''');
 a:=strpos(body,'  if jsonb_typeof(p_dados->''categorias'')');
 b:=strpos(body,'  if coalesce(p_dados->>''nome''');
 if a=0 or b<=a then raise exception 'Unexpected source function structure'; end if;
 body:=substr(body,1,a-1)||E'  if length(regexp_replace(p_dados->>''doc'',''[^0-9]'','''',''g'')) not in (11,14) then return jsonb_build_object(''ok'',false,''erro'',''campos_obrigatorios''); end if;\n'||substr(body,b);
 execute body;
 body:=replace(replace(pg_get_functiondef('public.notificar_convites_7dias()'::regprocedure),'notificar_convites_7dias','notificar_convites_cliente_7dias'),'fornecedor','cliente');
 execute body;
end $clone$;
revoke all on function public.get_convite_cliente(text) from public;
revoke all on function public.responder_convite_cliente(text,jsonb) from public;
grant execute on function public.get_convite_cliente(text),public.responder_convite_cliente(text,jsonb) to anon,authenticated;
revoke all on function public.notificar_convites_cliente_7dias() from public,anon,authenticated;
select cron.schedule('cliente-convites-7dias','23 5 * * *','select public.notificar_convites_cliente_7dias();');
select cron.schedule('cliente-convites-expirar-20dias','* * * * *','delete from public.cliente_convites where status=''pendente'' and created_at <= now() - interval ''20 days'';');
alter publication supabase_realtime add table public.cliente_convites;
